<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title><?=$this->data['page_title']?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- Bootstrap Core CSS -->
<link href="<?=$this->data['assets']?>/css/bootstrap.css" rel='stylesheet' type='text/css' />

<!-- Custom CSS -->
<link href="<?=$this->data['assets']?>/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS -->
<link href="<?=$this->data['assets']?>/css/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome icons CSS -->

 <!-- side nav css file -->
 <link href='<?=$this->data['assets']?>/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
 <!-- side nav css file -->
 
 <!-- js-->
<script src="<?=$this->data['assets']?>/js/jquery-1.11.1.min.js"></script>
<script src="<?=$this->data['assets']?>/js/modernizr.custom.js"></script>

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
<!--//webfonts--> 

<!-- Metis Menu -->
<script src="<?=$this->data['assets']?>/js/metisMenu.min.js"></script>
<script src="<?=$this->data['assets']?>/js/custom.js"></script>
<link href="<?=$this->data['assets']?>/css/custom.css" rel="stylesheet">
<!--//Metis Menu -->

</head> 
<body class="cbp-spmenu-push">
  <div class="main-content">
  <div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
    <!--left-fixed -navigation-->
    <aside class="sidebar-left">
      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <h1><a class="navbar-brand" href="<?=base_url()?>/index.php"><span class="fa fa-area-chart"></span> TalenTick<span class="dashboard_text">Design dashboard</span></a></h1>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="sidebar-menu">
              <li class="header">MAIN NAVIGATION</li>
              <li class="treeview">
                <a href="<?=base_url()?>/admin/index.php">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
              </li>  
              <li>
                <a href="#">
                  <i class="fa fa-bell"></i> <span>Notifications</span> </i><small class="label pull-right label-info1">08</small> 
                </a>
              </li> 
              <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Jobs</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="<?=base_url()?>/admin/search-jobs.php"><i class="fa fa-angle-right"></i> Search Jobs</a></li>
                  <li><a href="<?=base_url()?>/admin/jobs-list.php"><i class="fa fa-angle-right"></i> Jobs List</a></li>
                  <li><a href="<?=base_url()?>/admin/applied-jobs.php"><i class="fa fa-angle-right"></i> Applied Jobs</a></li> 
                </ul>
              </li> 
              
              </li>
              <li class="treeview">
                <a href="#">
                <i class="fa fa-user"></i>
                <span>Account</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="<?=base_url()?>/admin/profile-details.php"><i class="fa fa-angle-right"></i> My Profile</a></li>
                  <li><a href="<?=base_url()?>/admin/profile-update.php"><i class="fa fa-angle-right"></i> Update</a></li> 
                </ul>
              </li> 
              <li class="header">STUDENT</li>
              <li><a href="<?=base_url()?>/admin/settings.php"><i class="fa fa-cog text-red"></i> <span>Settings</span></a></li>
              <li><a href="<?=base_url()?>/actions/logout.php"><i class="fa fa-sign-out text-yellow"></i> <span>Logout</span></a></li> 
            </ul>
          </div>
          <!-- /.navbar-collapse -->
      </nav>
    </aside>
  </div>
    <!--left-fixed -navigation-->
    
    <!-- header-starts -->
    <div class="sticky-header header-section ">
      <div class="header-left">
        
        <!--toggle button start-->
        <button id="showLeftPush"><i class="fa fa-bars"></i></button>
        <!--toggle button end-->
        <div class="profile_details_left"><!--notifications of menu start -->
          <ul class="nofitications-dropdown">
           
            <li class="dropdown head-dpdn">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell"></i><span class="badge blue">4</span></a>
              <ul class="dropdown-menu">
                <li>
                  <div class="notification_header">
                    <h3>You have 3 new notification</h3>
                  </div>
                </li>
                <li><a href="#">
                  <div class="user_img"><img src="<?=$this->data['assets']?>/images/4.jpg" alt=""></div>
                   <div class="notification_desc">
                  <p>Lorem ipsum dolor amet</p>
                  <p><span>1 hour ago</span></p>
                  </div>
                  <div class="clearfix"></div>  
                 </a></li>
                 <li class="odd"><a href="#">
                  <div class="user_img"><img src="<?=$this->data['assets']?>/images/1.jpg" alt=""></div>
                   <div class="notification_desc">
                  <p>Lorem ipsum dolor amet </p>
                  <p><span>1 hour ago</span></p>
                  </div>
                   <div class="clearfix"></div> 
                 </a></li>
                 <li><a href="#">
                  <div class="user_img"><img src="<?=$this->data['assets']?>/images/3.jpg" alt=""></div>
                   <div class="notification_desc">
                  <p>Lorem ipsum dolor amet </p>
                  <p><span>1 hour ago</span></p>
                  </div>
                   <div class="clearfix"></div> 
                 </a></li>
                 <li>
                  <div class="notification_bottom">
                    <a href="#">See all notifications</a>
                  </div> 
                </li>
              </ul>
            </li> 
  
          </ul>
          <div class="clearfix"> </div>
        </div>
        <!--notification menu end -->
        <div class="clearfix"> </div>
      </div>
      <div class="header-right">
        
        
        <!--search-box-->
        <div class="search-box">
          <form class="input">
            <input class="sb-search-input input__field--madoka" placeholder="Search..." type="search" id="input-31" />
            <label class="input__label" for="input-31">
              <svg class="graphic" width="100%" height="100%" viewBox="0 0 404 77" preserveAspectRatio="none">
                <path d="m0,0l404,0l0,77l-404,0l0,-77z"/>
              </svg>
            </label>
          </form>
        </div><!--//end-search-box-->
        
        <div class="profile_details">   
          <ul>
            <li class="dropdown profile_details_drop">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <div class="profile_img"> 
                  <span class="prfil-img"><img src="<?=$this->data['assets']?>/images/2.jpg" alt=""> </span> 
                  <div class="user-name">
                    <p>Admin Name</p>
                    <span>Profile</span>
                  </div>
                  <i class="fa fa-angle-down lnr"></i>
                  <i class="fa fa-angle-up lnr"></i>
                  <div class="clearfix"></div>  
                </div>  
              </a>
              <ul class="dropdown-menu drp-mnu">
                <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li> 
                <li> <a href="#"><i class="fa fa-user"></i> My Account</a> </li>
                <li> <a href="#"><i class="fa fa-suitcase"></i> Profile</a> </li> 
                <li> <a href="#"><i class="fa fa-sign-out"></i> Logout</a> </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="clearfix"> </div>       
      </div>
      <div class="clearfix"> </div> 
    </div>
    <!-- //header-ends -->