<body class="cbp-spmenu-push">
  <div class="main-content">
  <div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
    <!--left-fixed -navigation-->
    <aside class="sidebar-left">
      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <h1><a class="navbar-brand" href="<?=base_url()?>/index.php"><span class="fa fa-area-chart"></span> TalenTick<span class="dashboard_text">Main Website</span></a></h1>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="sidebar-menu">
              <li class="header">MAIN NAVIGATION</li>
              <li class="treeview">
                <a href="<?=base_url()?>/admin/index.php">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
              </li>  
              <li>
                <a href="<?=base_url()?>/admin/notifications.php">
                  <i class="fa fa-bell"></i> <span>Notifications</span> 
                </a>
              </li> 
              <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Jobs</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu"> 
                  <li><a href="<?=base_url()?>/admin/job-list.php"><i class="fa fa-angle-right"></i> Jobs List</a></li>
                  <li><a href="<?=base_url()?>/admin/job-applications.php"><i class="fa fa-angle-right"></i> Job Applications</a></li> 
                </ul>
              </li> 

             <!--  <li class="treeview">
                <a href="#">
                <i class="fa fa-map"></i>
                <span>Locations</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu"> 
                  <li><a href="<?=base_url()?>/admin/location-states-list.php"><i class="fa fa-angle-right"></i> States List</a></li>
                  <li><a href="<?=base_url()?>/admin/location-state.php?action=add"><i class="fa fa-angle-right"></i> Add State</a></li> 
                  <li><a href="<?=base_url()?>/admin/location-districts-list.php"><i class="fa fa-angle-right"></i> District List</a></li>
                  <li><a href="<?=base_url()?>/admin/location-district.php?action=add"><i class="fa fa-angle-right"></i> Add District</a></li> 
                </ul>
              </li>   -->

              <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Departments</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu"> 
                  <li><a href="<?=base_url()?>/admin/department-list.php"><i class="fa fa-angle-right"></i> Deparment List</a></li>
                  <li><a href="<?=base_url()?>/admin/department.php?action=add"><i class="fa fa-angle-right"></i> Add Deparment</a></li> 
                </ul>
              </li> 
              
              
              <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Branches</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu"> 
                  <li><a href="<?=base_url()?>/admin/branch-list.php"><i class="fa fa-angle-right"></i> Branch List</a></li>
                  <li><a href="<?=base_url()?>/admin/branch.php?action=add"><i class="fa fa-angle-right"></i> Add branch</a></li> 
                </ul>
              </li> 
              
              <li class="treeview">
                <a href="#">
                <i class="fa fa-user"></i>
                <span>Students</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <!-- <li><a href="<?=base_url()?>/admin/student-search.php"><i class="fa fa-angle-right"></i> Search Student</a></li> -->
                  <li><a href="<?=base_url()?>/admin/student-list.php"><i class="fa fa-angle-right"></i> Students List</a></li>
                  <li><a href="<?=base_url()?>/admin/student-message.php"><i class="fa fa-angle-right"></i> Bulk Messsage </a></li> </li>

                </ul>
              </li>  
              
              <li class="treeview">
                <a href="#">
                <i class="fa fa-suitcase"></i>
                <span>Recruiters</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <!-- <li><a href="<?=base_url()?>/admin/recruiter-search.php"><i class="fa fa-angle-right"></i> Search Recruiter</a></li> -->
                  <li><a href="<?=base_url()?>/admin/recruiter-list.php"><i class="fa fa-angle-right"></i> Recruiter List</a></li> </li>
                  <li><a href="<?=base_url()?>/admin/recruiter-list.php?type=pending"><i class="fa fa-angle-right"></i> Pending Verifications</a></li>                     

                  <li><a href="<?=base_url()?>/admin/recruiter-message.php"><i class="fa fa-angle-right"></i> Bulk Messsage </a></li> </li>

                </ul>
              </li>  
              <li>
                <a href="<?=base_url()?>/admin/testimonials.php">
                  <i class="fa fa-edit"></i> <span>Testimonials</span> 
                </a>
              </li> 
               
              <li class="header">USER</li>
              <li class="treeview">
                <a href="#">
                <i class="fa fa-user"></i>
                <span>Account</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <!-- <li><a href="<?=base_url()?>/admin/profile-details.php"><i class="fa fa-angle-right"></i> My Profile</a></li> -->
               
                <li> <a href="<?=base_url()?>/admin/update-password.php"><i class="fa fa-lock"></i> Update Password</a> </li> 
                </ul>
              </li> 
              <!-- <li><a href="<?=base_url()?>/admin/settings.php"><i class="fa fa-cog text-red"></i> <span>Settings</span></a></li> -->
              <li><a href="<?=base_url()?>/actions/logout.php"><i class="fa fa-sign-out text-yellow"></i> <span>Logout</span></a></li> 
            </ul>
          </div>
          <!-- /.navbar-collapse -->
      </nav>
    </aside>
  </div>
    <!--left-fixed -navigation-->
    
    <!-- header-starts -->
    <div class="sticky-header header-section ">
      <div class="header-left">
        
       
        <!--notification menu end -->
        <div class="clearfix"> </div>
      </div>
      <div class="header-right">
        
        
        <div class="profile_details">   
          <ul>
            <li class="dropdown profile_details_drop">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <div class="profile_img"> 
                  <span class="prfil-img"><img src="<?=$this->data['assets']?>/images/2.jpg" alt=""> </span> 
                  <div class="user-name">
                    <p>Administrator</p>
                    <span>Profile</span>
                  </div>
                  <i class="fa fa-angle-down lnr"></i>
                  <i class="fa fa-angle-up lnr"></i>
                  <div class="clearfix"></div>  
                </div>  
              </a>
              <ul class="dropdown-menu drp-mnu">
                <!-- <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>  -->
                <!-- <li> <a href="<?=base_url()?>/admin/profile-details.php"><i class="fa fa-user"></i> My Profile</a> </li> -->
                <li> <a href="<?=base_url()?>/admin/update-password.php"><i class="fa fa-lock"></i> Update Password</a> </li> 
                <!-- <li> <a href="<?=base_url()?>/admin/profile-update.php"><i class="fa fa-edit"></i> Update Profile</a> </li>  -->
                <li> <a href="<?=base_url()?>/actions/logout.php"><i class="fa fa-sign-out"></i> Logout</a> </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="clearfix"> </div>       
      </div>
      <div class="clearfix"> </div> 
    </div>
    <!-- //header-ends -->