
    <!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">  
        
          <div class="col-md-3 widget widget1">
            <div class="r3_counter_box">
                    <i class="pull-left fa fa-laptop user1 icon-rounded"></i>
                    <div class="stats">
                      <h5><strong><?=$this->data['recruiter_count'] ?></strong></h5>
                      <span>Total Recruiters</span>
                    </div>
                </div>
          </div>
          <div class="col-md-3 widget widget1">
            <div class="r3_counter_box">
                    <i class="pull-left fa fa-money user2 icon-rounded"></i>
                    <div class="stats">
                      <h5><strong><?=$this->data['job_count'] ?></strong></h5>
                      <span>Jobs</span>
                    </div>
                </div>
          </div> 

          <div class="col-md-3 widget ">
            <div class="r3_counter_box">
                    <i class="pull-left fa fa-bell dollar2 icon-rounded"></i>
                    <div class="stats">
                      <h5><strong><?=$this->data['notification_count'] ?></strong></h5>
                      <span>Notifications</span>
                    </div>
                </div>
           </div>

          <div class="clearfix"> </div>
    </div> 
      
   
      
    </div>
        
      </div>
    </div>