<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="forms">
          <h2 class="title1">Update Profile</h2>  

          <div class="row"> 
            <div class="form-three widget-shadow">

              <form enctype='multipart/form-data' action="<?=base_url()?>/student/actions/profile-update-action.php" method="post" class="form-horizontal"   >

                <div class="form-group">
                  <label for="firstname" class="col-sm-2 control-label">First Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="firstname" name="firstname"  value="<?=$this->data['profile_details']['firstname']?> " readonly />
                  </div>
                </div> 

                <div class="form-group">
                  <label for="lastname" class="col-sm-2 control-label">Last Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="lastname" name="lastname"  value="<?=$this->data['profile_details']['lastname']?> " readonly />
                  </div>
                </div> 


                <div class="form-group">
                  <label for="gender" class="col-sm-2 control-label">Gender</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gender" name="gender"  value="<?=$this->data['profile_details']['gender']?> " readonly />
                  </div>
                </div> 

                
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">DOB</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="dob" name="gender"  value="<?=$this->data['profile_details']['dob']?> " readonly />
                  </div>
                </div> 

                


                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="email" required="required" class="form-control1" id="email" name="email"  value="<?=$this->data['profile_details']['email']?> " >
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">mobile_number</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="mobile_number" name="mobile_number"  value="<?=$this->data['profile_details']['mobile_number']?> " >
                  </div>
                </div> 


state_id
district_id
   

                
                <div class="form-group">
                  <label for="district" class="col-sm-2 control-label">district</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="district" name="district"  value="<?=$this->data['profile_details']['dob']?> " >
                  </div>
                </div>  
                
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">state</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="state" name="state"  value="<?=$this->data['profile_details']['state']?> " >
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="address" class="col-sm-2 control-label">address</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="address" name="address"  value="<?=$this->data['profile_details']['address']?> " >
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="addressline2" class="col-sm-2 control-label">addressline2</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="addressline2" name="addressline2"  value="<?=$this->data['profile_details']['addressline2']?> " >
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="addressline3" class="col-sm-2 control-label">addressline3</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="addressline3" name="addressline3"  value="<?=$this->data['profile_details']['addressline3']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">pincode</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="pincode" name="pincode"  value="<?=$this->data['profile_details']['pincode']?> " >
                  </div>
                </div>  

branch_id   
                <div class="form-group">
                  <label for="branch" class="col-sm-2 control-label">branch</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="branch" name="branch"  value="<?=$this->data['profile_details']['branch']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="department" class="col-sm-2 control-label">department</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="department" name="department"  value="<?=$this->data['profile_details']['department']?> " >
                  </div>
                </div>  
student_id  
                <div class="form-group">
                  <label for="cgpa" class="col-sm-2 control-label">cgpa</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="cgpa" name="cgpa"  value="<?=$this->data['profile_details']['cgpa']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="gpg" class="col-sm-2 control-label">gpg</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gpg" name="gpg"  value="<?=$this->data['profile_details']['gpg']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="gug" class="col-sm-2 control-label">gug</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gug" name="gug"  value="<?=$this->data['profile_details']['gug']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="gplus" class="col-sm-2 control-label">gplus</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gplus" name="gplus"  value="<?=$this->data['profile_details']['gplus']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="g10" class="col-sm-2 control-label">g10</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="g10" name="g10"  value="<?=$this->data['profile_details']['g10']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="backlogs" class="col-sm-2 control-label">backlogs</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="backlogs" name="backlogs"  value="<?=$this->data['profile_details']['backlogs']?> " >
                  </div>
                </div>  


                <div class="form-group">
                  <label for="highest_qualification" class="col-sm-2 control-label">highest_qualification</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="highest_qualification" name="highest_qualification"  value="<?=$this->data['profile_details']['highest_qualification']?> " >
                  </div>
                </div>  

                <div class="form-group">
                  <label for="resume" class="col-sm-2 control-label">resume</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="resume" name="resume"  value="<?=$this->data['profile_details']['resume']?> " >
                  </div>
                </div>
 
                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Image  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" id="image" name="image" >
                  </div>
                  <div class="col-sm-4"> 
                    <img src="<?=base_url()?>/uploads/images/<?=$this->data['profile_details']['image']?>">
                  </div> 
                </div> 


                <div class="form-group"> 
                  <label for="pincode" class="col-sm-2 control-label">   </label>
                  <div class="col-md-8"></div>
                   <div class="col-md-4">
                    <input type="hidden" name="user_id" value="<?=$this->data['profile_details']['user_id']?> " >
                    <input type="hidden" name="status" value="<?=$this->data['profile_details']['status']?> " >
                    <input type="submit" class="btn btn-info"  value="Update Profile" >
                  </div>
                </div> 

 
  
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>