<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="forms">
          <h2 class="title1">Update Profile</h2>  

          <div class="row"> 
            <div class="form-three widget-shadow">

              <form enctype='multipart/form-data' action="<?=base_url()?>/student/actions/profile-update-action.php" method="post" class="form-horizontal"   >

                <div class="form-group">
                  <label for="firstname" class="col-sm-2 control-label">First Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="firstname" name="firstname"  value="<?=$this->data['profile_details']['firstname']?> " readonly />
                  </div>
                </div> 

                <div class="form-group">
                  <label for="lastname" class="col-sm-2 control-label">Last Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="lastname" name="lastname"  value="<?=$this->data['profile_details']['lastname']?> " readonly />
                  </div>
                </div>  

                 <div class="form-group">
                  <label for="gender" class="col-sm-2 control-label">Gender</label> 
                    <div class="col-sm-8">  
                      <select name="gender" id="job_type" class="form-control1"> 
                          <option 
                          <?php if ($this->data['profile_details']['gender'] == "Male"): ?>
                            selected = "selected"
                          <?php endif ?>  value="Male" >Male</option> 
                          <option 
                          <?php if ($this->data['profile_details']['gender'] == "Female"): ?>
                            selected = "selected"
                          <?php endif ?> value="Female" >Female</option> 
                          <option
                          <?php if ($this->data['profile_details']['gender'] == "Other"): ?>
                            selected = "selected"
                          <?php endif ?> value="Other" >Other</option> 
                          
                    </select>
                  </div> 
                </div> 
                
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">DOB</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="dob" name="gender"  value="<?=$this->data['profile_details']['dob']?> " readonly />
                  </div>
                </div>  

                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="email" required="required" class="form-control1" id="email" name="email"  value="<?=$this->data['profile_details']['email']?> " >
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">mobile_number</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="mobile_number" name="mobile_number"  value="<?=$this->data['profile_details']['mobile_number']?> " >
                  </div>
                </div>  
               
                <div class="form-group">
                  <label for="state_id" class="col-sm-2 control-label">Select State*</label>
                  <div class="col-sm-8">
                    <select name="state_id" id="state_id" class="form-control1" onchange="updateDistricts()" >
                      <option >--Select State--</option>  
                      <?php foreach ($this->data['states'] as $state ) { ?>
                       <option value="<?=$state['id'] ?>" ><?=$state['name'] ?></option> 
                       <?php }?>
                    </select>
                  </div>
                </div>

                <div class="form-group">
                  <label for="district_id" class="col-sm-2 control-label">Select District </label>
                  <div class="col-sm-8">
                    <select disabled="disabled" name="district_id" id="district_id" class="form-control1"> 
                        <option>--Select a State First-- </option>  
                    </select>
                  </div>
                </div> 

                
                <div class="form-group">
                  <label for="address" class="col-sm-2 control-label">Address</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="address" name="address"  value="<?=$this->data['profile_details']['address']?> " >
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="addressline2" class="col-sm-2 control-label">Address Line2</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="addressline2" name="addressline2"  value="<?=$this->data['profile_details']['addressline2']?> " >
                  </div>
                </div>  

                

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Pincode</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="pincode" name="pincode"  value="<?=$this->data['profile_details']['pincode']?> " >
                  </div>
                </div>   

                <div class="form-group">
                  <label for="branch_id" class="col-sm-2 control-label">Branch*</label>
                  <div class="col-sm-8">
                    <select  name="branch_id" id="branch_id" class="form-control1"   > 
                      <?php foreach ($this->data['branches'] as $branches ) { ?>
                       <option value="<?=$branches['id'] ?>" ><?=$branches['branch'] ?> (<?=$branches['department']?>) </option> 
                       <?php }?>
                    </select>
                  </div>
                </div>
   
                <div class="form-group">
                  <label for="cgpa" class="col-sm-2 control-label">CGPA</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="cgpa" name="cgpa"  value="<?=$this->data['profile_details']['cgpa']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="gpg" class="col-sm-2 control-label">Grade in PostGraduation</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gpg" name="gpg"  value="<?=$this->data['profile_details']['gpg']?> " >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="gug" class="col-sm-2 control-label">Grade in Graduation</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gug" name="gug"  value="<?=$this->data['profile_details']['gug']?>" >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="gplus" class="col-sm-2 control-label">Grade in +2</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gplus" name="gplus"  value="<?=$this->data['profile_details']['gplus']?>" >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="g10" class="col-sm-2 control-label">Grade in 10th </label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="g10" name="g10"  value="<?=$this->data['profile_details']['g10']?>" >
                  </div>
                </div> 


                <div class="form-group">
                  <label for="backlogs" class="col-sm-2 control-label">Backlogs Count</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="backlogs" name="backlogs"  value="<?=$this->data['profile_details']['backlogs']?>" >
                  </div>
                </div>  


                <div class="form-group">
                  <label for="highest_qualification" class="col-sm-2 control-label">Highest Qualification</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="highest_qualification" name="highest_qualification"  value="<?=$this->data['profile_details']['highest_qualification']?> " >
                  </div>
                </div>  

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Resume  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" id="resume" name="resume" required="required" >
                  </div>
                  <div class="col-sm-4"> 
                    <?php if (isset($this->data['profile_details']['resume'])) { ?> 
                   
                    <a href="<?=base_url()?>/uploads/resumes/<?=$this->data['profile_details']['resume']?>"> <i class="fa fa-file"></i> View Resume </a>
                  <?php } ?>

                  </div> 
                </div>  
 
                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Image  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" id="image" name="image" >
                  </div>
                  <div class="col-sm-4"> 
                    <img src="<?=base_url()?>/uploads/images/<?=$this->data['profile_details']['image']?>">
                  </div> 
                </div> 


                <div class="form-group"> 
                  <label for="pincode" class="col-sm-2 control-label">   </label>
                  <div class="col-md-8"></div>
                   <div class="col-md-4">
                    <input type="hidden" name="user_id" value="<?=$this->data['profile_details']['user_id']?> " >
                    <input type="hidden" name="status" value="<?=$this->data['profile_details']['status']?> " >
                    <input type="submit" class="btn btn-info"  value="Update Profile" >
                  </div>
                </div> 

 
  
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>



    <script type="text/javascript"> 

        function updateDistricts() {   

        var selectedState = document.getElementById('state_id');

        var districtDropdown =  document.getElementById('district_id');

        districtDropdown.removeAttribute("disabled");

        console.log( selectedState.value ); 

        var state_id = selectedState.value ; 

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {

            //console.log(this.responseText) ;

            if(this.responseText != "") {

              var response = JSON.parse(this.responseText);  
              //console.log(response) ;

              var districts = response.districts;

              //console.log(districts) ;

              districtDropdown.innerText = null; 

              var element = document.createElement("option");
              element.innerText = "--Select District--"; 
              districtDropdown.append(element);

               for (district in districts) { 

                item = districts[district] ; 

                //console.log(districts[district]) ;

                var element = document.createElement("option");
                element.innerText = item['district']; 
                element.value = item['id']; 
                districtDropdown.append(element);
              }
              
            }
          }
        };
        xmlhttp.open("GET", "<?=base_url()?>/apis/lists.php?type=districts&state="+state_id, true);
        xmlhttp.send();  

    } 

    </script>