<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="forms">
          <h2 class="title1">Update Profile</h2>  

          <div class="row"> 
            <div class="form-three widget-shadow">

              <form enctype='multipart/form-data' name="update_form"action="<?=base_url()?>/student/actions/profile-update-action.php" method="post" class="form-horizontal"   >

                <div class="form-group">
                  <label for="firstname" class="col-sm-2 control-label">First Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="firstname" name="firstname"  value="<?=$this->data['profile_details']['firstname']?>" readonly />
                  </div>
                </div> 

                <div class="form-group">
                  <label for="lastname" class="col-sm-2 control-label">Last Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="lastname" name="lastname"  value="<?=$this->data['profile_details']['lastname']?>" readonly />
                  </div>
                </div>  

                 <div class="form-group">
                  <label for="gender" class="col-sm-2 control-label">Gender</label> 
                    <div class="col-sm-8">  
                      <select name="gender" id="job_type" class="form-control1"> 
                          <option 
                          <?php if ($this->data['profile_details']['gender'] == "Male"): ?>
                            selected = "selected"
                          <?php endif ?>  value="Male" >Male</option> 
                          <option 
                          <?php if ($this->data['profile_details']['gender'] == "Female"): ?>
                            selected = "selected"
                          <?php endif ?> value="Female" >Female</option> 
                          <option
                          <?php if ($this->data['profile_details']['gender'] == "Other"): ?>
                            selected = "selected"
                          <?php endif ?> value="Other" >Other</option> 
                          
                    </select>
                  </div> 
                </div> 
                
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">DOB</label>
                  <div class="col-sm-8">
                    <input type="date" class="form-control1" id="dob" name="dob" min="1989-01-01" max="2001-12-31" min="<?=(date('d-m-Y', strtotime('-50 year')))?>" max="<?=(date('d-m-Y', strtotime('-20 year')))?>"  value="<?=$this->data['profile_details']['dob']?>" required="required" />
                  </div>
                </div>  

                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="email" required="required" class="form-control1" id="email" onchange="return ValidateEmail()"name="email"  value="<?=$this->data['profile_details']['email']?>" readonly />
                    <label class="errortext" style="display:no ne; color:red" id="email"></label>
                  <div id="email_error" style="color:red;" >  </div>
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">Mobile Number</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="mobile_number"onchange="return Validatemobile_number()" name="mobile_number"  value="<?=$this->data['profile_details']['mobile_number']?>" >
                    <label class="errortext" style="display:no ne; color:red" id="mobile_number"></label>
                  <div id="mobile_number_error" style="color:red;" >  </div>

                  </div>
                </div>  
               
                <div class="form-group">
                  <label for="state_id" class="col-sm-2 control-label">Select State</label>
                  <div class="col-sm-8">
                    <select name="state_id" id="state_id" class="form-control1" onchange="updateDistricts()" >
                      <option >--Select State--</option>  
                      <?php foreach ($this->data['states'] as $state ) { ?>
                       <option value="<?=$state['id'] ?>" ><?=$state['name'] ?></option> 
                       <?php }?>
                    </select>
                  </div>
                </div>

                <div class="form-group">
                  <label for="district_id" class="col-sm-2 control-label">Select District </label>
                  <div class="col-sm-8">
                    <select disabled="disabled" name="district_id" id="district_id" class="form-control1"> 
                        <option>--Select a State First-- </option>  
                    </select>
                  </div>
                </div> 

                
                <div class="form-group">
                  <label for="address" class="col-sm-2 control-label">Address</label>
                  <div class="col-sm-8">
                    <input type="textarea" class="form-control1" id="address" name="address"  value="<?=$this->data['profile_details']['address']?>" required >
                  </div>
                </div>  

                
                <div class="form-group">
                  <label for="addressline2" class="col-sm-2 control-label">Address Line2</label>
                  <div class="col-sm-8">
                    <input type="textarea" class="form-control1" id="addressline2" name="addressline2"  value="<?=$this->data['profile_details']['addressline2']?>" required >
                  </div>
                </div>  

                

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Pincode</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="pincode" onchange="return ValidatePincode()" name="pincode"  value="<?=$this->data['profile_details']['pincode']?>" >
                    <label class="errortext" style="display:no ne; color:red" id="pincode"></label>
                  <div id="pincode_error" style="color:red;" >  
                  </div>
                  </div>
                </div>   

                <div class="form-group">
                  <label for="branch_id" class="col-sm-2 control-label">Branch</label>
                  <div class="col-sm-8">
                    <select  name="branch_id" id="branch_id" class="form-control1" required="required"   > 
                      <option>--Select Branch-- </option>  
                      <?php foreach ($this->data['branches'] as $branches ) { ?>
                       <option value="<?=$branches['id'] ?>" ><?=$branches['branch'] ?> (<?=$branches['department']?>) </option> 
                       <?php }?>
                    </select>
                  </div>
                </div>
   
                <div class="form-group">
                  <label for="cgpa" class="col-sm-2 control-label">Percentage</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" onchange="return Validate_Percentage()" id="cgpa"  name="cgpa"  value="<?=$this->data['profile_details']['cgpa']?>" >
                    <label class="errortext" style="display:no ne; color:red" id="cgpa"></label>
                  <div id="cgpa_error" style="color:red;" >  
                  </div>
                </div> 
              </div>


                <div class="form-group">
                  <label for="gpg" class="col-sm-2 control-label">Percentage in Post Graduation</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gpg" onchange="return Validate_Post_Graduation()" name="gpg"  value="<?=$this->data['profile_details']['gpg']?>" >
                     <label class="errortext" style="display:no ne; color:red" id="gpg"></label>
                  <div id="gpg_error" style="color:red;" >  
                  </div>

                  </div>
                </div> 

                <div class="form-group">
                  <label for="gug" class="col-sm-2 control-label">Percentage in Graduation</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gug" onchange="return Validate_Graduation()" name="gug"  value="<?=$this->data['profile_details']['gug']?>" >
                     <label class="errortext" style="display:no ne; color:red" id="gug"></label>
                  <div id="gug_error" style="color:red;" >  
                  </div>

                  </div>
                </div> 


                <div class="form-group">
                  <label for="gplus" class="col-sm-2 control-label">Percentage in +2</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="gplus" onchange="return validatePlusTwo()"name="gplus"  value="<?=$this->data['profile_details']['gplus']?>" >
                      <label class="errortext" style="display:no ne; color:red" id="gplus"></label>
                  <div id="gplus_error" style="color:red;" >  
                  </div>

                  </div>
                </div> 


                <div class="form-group">
                  <label for="g10" class="col-sm-2 control-label">Percentage in 10th </label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="g10" onchange=" return Validateten()" name="g10"  value="<?=$this->data['profile_details']['g10']?>" >
                     <label class="errortext" style="display:no ne; color:red" id="g10"></label>
                  <div id="g10_error" style="color:red;" >  
                  </div>
                  </div>
                </div> 


                <div class="form-group">
                  <label for="backlogs" class="col-sm-2 control-label">Backlogs Count</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="backlogs" onchange="return Validatebacklogs()" name="backlogs"  value="<?=($this->data['profile_details']['backlogs']??0) ?>" >
                    <label class="errortext" style="display:no ne; color:red" id="Backlogs"></label>
                  <div id="backlogs_error" style="color:red;" >  
                  </div>

                  </div>
                 </div>  

                 <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">SSLC Certificate  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" id="sslc_certificate" name="sslc_certificate" 
                    <?=(!empty($this->data['profile_details']['sslc_certificate']))? "" : ' required="required"'?>  accept="pdf"  >
                  </div>
                  <div class="col-sm-4"> 
                    <?php if (isset($this->data['profile_details']['sslc_certificate'])) { ?> 
                   
                    <a href="<?=base_url()?>/uploads/resumes/<?=$this->data['profile_details']['sslc_certificate']?>"> <i class="fa fa-file"></i> View SSLC Certificate </a>
                  <?php } ?> 

                  </div> 
                </div>  

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">HigherSecondary Certificate  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" id="highersecondary_certificate" name="highersecondary_certificate" 

                    <?=(!empty($this->data['profile_details']['highersecondary_certificate']))? "" : ' required="required"'?>  accept="pdf"  >
                  </div>
                  <div class="col-sm-4"> 
                    <?php if (isset($this->data['profile_details']['highersecondary_certificate'])) { ?> 
                   
                    <a href="<?=base_url()?>/uploads/resumes/<?=$this->data['profile_details']['highersecondary_certificate']?>"> <i class="fa fa-file"></i> View HigherSecondary Certificate </a>
                  <?php } ?>

                  </div> 
                </div>  

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Resume  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" id="resume" name="resume" 
                    <?=(!empty($this->data['profile_details']['resume']))? "" : ' required="required"'?>  accept="pdf"  >
                  </div>
                  <div class="col-sm-4"> 
                    <?php if (isset($this->data['profile_details']['resume'])) { ?> 
                   
                    <a href="<?=base_url()?>/uploads/resumes/<?=$this->data['profile_details']['resume']?>"> <i class="fa fa-file"></i> View Resume </a>
                  <?php } ?>

                  </div> 
                </div>  
 
                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Image  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" accept="png" id="image" name="image" >
                  </div>
                  <div class="col-sm-4"> 
                    <img class="img img-responsive" width="150" src="<?=base_url()?>/uploads/images/<?=$this->data['profile_details']['image']?>">
                  </div> 
                </div> 


                <div class="form-group"> 
                  <label for="pincode" class="col-sm-2 control-label">   </label>
                  <div class="col-md-8"></div>
                   <div class="col-md-4">
                    <input type="hidden" name="user_id" value="<?=$this->data['profile_details']['user_id']?>" >
                    <input type="hidden" name="payment_id" value="<?=$this->data['profile_details']['payment_id']?>" >
                    <input type="hidden" name="payment_status" value="<?=$this->data['profile_details']['payment_status']?>" >
                    <input type="hidden" name="payment_method" value="<?=$this->data['profile_details']['payment_method']?>" >
                    <input type="hidden" name="payment_date" value="<?=$this->data['profile_details']['payment_date']?>" > 

                    <input type="submit" class="btn btn-info"  value="Update Profile" >
                  </div>
                </div> 

 
  
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>



    <script type="text/javascript"> 

        function updateDistricts() {   

        var selectedState = document.getElementById('state_id');

        var districtDropdown =  document.getElementById('district_id');

        districtDropdown.removeAttribute("disabled");

        console.log( selectedState.value ); 

        var state_id = selectedState.value ; 

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {

            //console.log(this.responseText) ;

            if(this.responseText != "") {

              var response = JSON.parse(this.responseText);  
              //console.log(response) ;

              var districts = response.districts;

              //console.log(districts) ;

              districtDropdown.innerText = null; 

              var element = document.createElement("option");
              element.innerText = "--Select District--"; 
              districtDropdown.append(element);

               for (district in districts) { 

                item = districts[district] ; 

                //console.log(districts[district]) ;

                var element = document.createElement("option");
                element.innerText = item['district']; 
                element.value = item['id']; 
                districtDropdown.append(element);
              }
              
            }
          }
        };
        xmlhttp.open("GET", "<?=base_url()?>/apis/lists.php?type=districts&state="+state_id, true);
        xmlhttp.send();  

    } 
    var  up_form = document.update_form;
    function ValidateEmail()
{
  document.getElementById('email_error').innerHTML = "" ;
 var email = document.getElementById('email');
   var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
   if (!filter.test(email.value)) 
{
    email.value="";
    document.getElementById('email').focus();
    document.getElementById('email_error').innerHTML ="Error: Please enter email!" ; 
    
    return false;
    }
return true;
}
function Validatemobile_number()
{
 document.getElementById('mobile_number_error').innerHTML = "" ;
if(document.update_form.mobile_number.value == "" ||
isNaN(document.update_form.mobile_number.value) ||
document.update_form.mobile_number.value.length != 10 )
{
 document.getElementById('mobile_number_error').innerHTML = "Please provide a Mobile No upto 10 digit" ;     

  
document.getElementById('mobile_number').focus();
return false;
}
var pattern = new RegExp("^([6-9]{1})([0-9]{9})$");
if(!pattern.test(document.update_form.mobile_number.value))
{
 document.getElementById('mobile_number_error').innerHTML = "Phone Number is invalid!" ; 
update_form.mobile_number.focus();
return false;
}
return true;
}
function ValidatePincode()
{
 document.getElementById('pincode_error').innerHTML = "" ;
if(document.update_form.pincode.value == "" ||
isNaN(document.update_form.pincode.value) ||
document.update_form.pincode.value.length != 6 )
{
 document.getElementById('pincode_error').innerHTML = "Please provide a valid pincode with 6 digits" ;     

  
document.getElementById('pincode').focus();
return false;
}
var pattern = new RegExp("^([1-9]{1})([0-9]{5})$");
if(!pattern.test(document.update_form.pincode.value))
{
 document.getElementById('pincode_error').innerHTML = "Pincode is invalid!" ; 
update_form.pincode.focus();
return false;
}
return true;
}
function Validate_Percentage()
{
document.getElementById('cgpa_error').innerHTML = "" ;
if(document.update_form.cgpa.value == "" ||
isNaN(document.update_form.cgpa.value) ||
document.update_form.cgpa.value.length != 2 )

{
 document.getElementById('cgpa_error').innerHTML = "Please provide a valid CGPA " ;      
document.getElementById('cgpa').focus();
return false;
}
var pattern = document.getElementById('cgpa').value;
if(isNaN(pattern))
{
 document.getElementById('cgpa_error').innerHTML = "CGPA is invalid!" ; 
update_form.cgpa.focus();
return false;
}
return true;
}




function Validate_Post_Graduation()
{
document.getElementById('gpg_error').innerHTML = "" ;
if(document.update_form.gpg.value == "" ||
isNaN(document.update_form.gpg.value) ||
document.update_form.gpg.value.length != 2 )

{
 document.getElementById('gpg_error').innerHTML = "Please provide a valid CGPA " ;      
document.getElementById('gpg').focus();
return false;
}
var pattern = document.getElementById('gpg').value;
if(isNaN(pattern))
{
 document.getElementById('gpg_error').innerHTML = "CGPA is invalid!" ; 
update_form.gpg.focus();
return false;
}
return true;

}

function Validate_Graduation()
{
document.getElementById('gug_error').innerHTML = "" ;
if(document.update_form.gug.value == "" ||
isNaN(document.update_form.gug.value) ||
document.update_form.gug.value.length != 2 )

{
 document.getElementById('gug_error').innerHTML = "Please provide a valid CGPA " ;      
document.getElementById('gug').focus();
return false;
}
var pattern = document.getElementById('gug').value;
if(isNaN(pattern))
{
 document.getElementById('gug_error').innerHTML = "CGPA is invalid!" ; 
update_form.gug.focus();
return false;
}
return true;


}
function Validate_plusTwo()
{
  document.getElementById('gplus_error').innerHTML = "" ;
if(document.update_form.gplus.value == "" ||
isNaN(document.update_form.gplus.value) ||
document.update_form.gplus.value.length != 2 )

{
 document.getElementById('gplus_error').innerHTML = "Please provide a valid CGPA " ;      
document.getElementById('gplus').focus();
return false;
}
var pattern = document.getElementById('gplus').value;
if(isNaN(pattern))
{
 document.getElementById('gplus_error').innerHTML = "CGPA is invalid!" ; 
update_form.gplus.focus();
return false;
}
return true;


}
function Validate_tenth()
{
  document.getElementById('g10_error').innerHTML = "" ;
if(document.update_form.g10.value == "" ||
isNaN(document.update_form.g10.value) ||
document.update_form.g10.value.length != 2 )

{
 document.getElementById('g10_error').innerHTML = "Please provide a valid CGPA " ;      
document.getElementById('g10').focus();
return false;
}
var pattern = document.getElementById('g10').value;
if(isNaN(pattern))
{
 document.getElementById('g10_error').innerHTML = "CGPA is invalid!" ; 
update_form.g10.focus();
return false;
}
return true;
  
}
    </script>