<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="tables">
          <h2 class="title1">Departments</h2> 

             <?=$this->data['op_status']??""?>  
          
          <div class="bs-example widget-shadow" data-example-id="hoverable-table"> 
            <h4>Department List:</h4>
            <table id="datatable"  class="table table-hover"> 

             <!--   `id`, `department_id`, `district`, `status`  -->

              <thead> <tr> 
                <th>#</th> <th>Name</th>    <th>Actions</th> </tr> 
              </thead> 
              <tbody> 
                <?php $i = 1;  foreach ($this->data['departments']  as $department) { ?> 
                <tr> 
                  <th scope="row"><?=$i++?></th> 
                  <td><?=$department['department']?></td>  
                  <td> <a href="<?=base_url().'/'.$this->data['login_type'].'/department.php?id='.$department['id']?>">Edit</a> </td> 
                </tr>  
                <?php } ?>
              </tbody> 
            </table>
          </div>
          
          
        </div>
      </div>
    </div>