<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">Notifications Page</h2>
         
        <div class="col-md-12  widget-shadow">
          <div class="panel-default">
            <div class="panel-heading">
              Inbox 
            </div>
            <div class="inbox-page">
          <h4>Today</h4>
          <div class="inbox-row widget-shadow" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="mail "> <input type="checkbox" class="checkbox"> </div>
            <div class="mail"><img src="images/i1.png" alt=""/></div>
            <div class="mail mail-name"> <h6>Alexander</h6> </div>
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              <div class="mail"><p>Nullam quis risus eget urna mollis ornare accusamus terry </p></div>
            </a>
            <div class="mail-right dots_drop">
              <div class="dropdown">
                <a href="#"  data-toggle="dropdown" aria-expanded="false">
                  <p><i class="fa fa-ellipsis-v mail-icon"></i></p>
                </a>
                <ul class="dropdown-menu float-right">
                  <li>
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                      <i class="fa fa-reply mail-icon"></i>
                      Reply
                    </a>
                  </li>
                  <li>
                    <a href="#" title="">
                      <i class="fa fa-download mail-icon"></i>
                      Archive
                    </a>
                  </li>
                  <li>
                    <a href="#" class="font-red" title="">
                      <i class="fa fa-trash-o mail-icon"></i>
                      Delete
                    </a>
                  </li>
                </ul>
              </div> 
            </div>
            <div class="mail-right"><p>30th Nov</p></div>
            <div class="clearfix"> </div>
            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
              <div class="mail-body">
                <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor.</p>
                <form>
                  <input type="text" placeholder="Reply to sender" required="">
                  <input type="submit" value="Send">
                </form>
              </div>
            </div>
          </div> 
          </div>
        </div> 
        <div class="inbox-page row">
          <h4>Older Messages</h4>
          <div class="inbox-row widget-shadow">
            <div class="mail "> <input type="checkbox" class="checkbox"> </div>
            <div class="mail"><img src="images/i2.png" alt=""/></div>
            <div class="mail mail-name"><h6> Michael</h6></div>
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseNine" aria-expanded="true" aria-controls="collapsenine">
              <div class="mail"><p>Mollis nullam quis risus ornare vel leo dolor sit amet</p></div>
            </a>
            <div class="mail-right dots_drop">
              <div class="dropdown">
                <a href="#"  data-toggle="dropdown" aria-expanded="false">
                  <p><i class="fa fa-ellipsis-v mail-icon"></i></p>
                </a>
                <ul class="dropdown-menu float-right">
                  <li>
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseNine" aria-expanded="true" aria-controls="collapseNine">
                      <i class="fa fa-reply mail-icon"></i>
                      Reply
                    </a>
                  </li>
                  <li>
                    <a href="#" title="">
                      <i class="fa fa-download mail-icon"></i>
                      Archive
                    </a>
                  </li>
                  <li>
                    <a href="#" class="font-red" title="">
                      <i class="fa fa-trash-o mail-icon"></i>
                      Delete
                    </a>
                  </li>
                </ul>
              </div> 
            </div>
            <div class="mail-right"><p>29th Nov</p></div>
            <div class="clearfix"> </div>
            <div id="collapseNine" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingnine">
              <div class="mail-body">
                <p>Skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.</p>
                <form>
                  <input type="text" placeholder="Reply to sender" required="">
                  <input type="submit" value="Send">
                </form>
              </div>
            </div>
          </div>   
            
      </div>
        </div>
        <div class="clearfix"> </div> 
      </div>
        
      </div>
    </div>