<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="tables">
          <h2 class="title1">Tables</h2>  

            <div class="bs-example widget-shadow" data-example-id="hoverable-table"> 
            <h4>Hover Rows Table:</h4>
            <table id="datatable"  class="table table-hover"> 

             <!--  `id`, `recruiter`, `job_title`, -->

              <thead> <tr> 
                <th>#</th> <th>Company Name</th> <th>Email</th> <th>Phone</th> <th>License</th>  <th>Actions</th> </tr> 
              </thead> 
              <tbody> 
                <?php $i = 1;  foreach ($this->data['recruiters']  as $recruiter) { ?> 
                <tr> 
                  <th scope="row"><?=$i++?></th> 
                  <td><?=$recruiter['company_name']?></td> 
                  <td><?=$recruiter['email']?></td>
                  <td><?=$recruiter['phone']?> </td> 
                  <td><?=$recruiter['license'] ?></td> 
                  <td> <a href="<?=base_url().'/'.$this->data['login_type'].'/recruiter-details.php?id='.$recruiter['id']?>">View</a> </td> 
                </tr>  
                <?php } ?>
              </tbody> 
            </table>
          </div>
          
          
        </div>
      </div>
    </div>