
    <!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="tables">
          <h2 class="title1">Testimonials</h2> 
 


            <div class="bs-example widget-shadow" data-example-id="hoverable-table"> 
            <h4>Testimonials List:</h4>
            <table id="datatable"  class="table table-hover"> 

             <!--  `id`, `recruiter`, `job_title`, -->

              <thead> <tr> 
                <th>#</th> <th>UserType</th> <th>Status</th> <th>Created At</th>  <th>Actions</th> </tr> 
              </thead> 
              <tbody> 
                <?php $i = 1;  foreach ($this->data['testimonials']  as $testimonial) { 

                  $testimonial_date=date_create($testimonial['created_at']);  ?>  
                <tr> 
                  <th scope="row"><?=$i++?></th> 
                  <td><?=$testimonial['user_type']?></td> 
                  <td><?=$testimonial['status']?></td>
                  <td><?=date_format($testimonial_date,"M/d");?></td>  
                  <td> <a href="<?=base_url().'/'.$this->data['login_type'].'/testimonial-details.php?id='.$testimonial['id']?>">View</a> </td> 
                </tr>  
                <?php } ?>
              </tbody> 
            </table>
          </div>
          
          
        </div>
      </div>
    </div>