<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">Testimonial Details</h2> 
             <?=$this->data['op_status']??""?>  
        <div class="blank-page widget-shadow scroll" id="style-2 div1">
          <p> User Type: <?=$this->data['testimonial_details']['user_type']?> </p>
          <p> Description: <?=$this->data['testimonial_details']['description']?> </p> 
          <p> Status: <?=$this->data['testimonial_details']['status']?> </p> 
          <p> Show In Web: <?=$this->data['testimonial_details']['show_in_web']?> </p>  

           <div> <br>
              <a class="btn btn-success btn-sm" href="<?=base_url()?>/admin/actions/testimonial-update-action.php?id=<?=$this->data['testimonial_details']['id']?>&action=approved">Approve</a>  

              <a class="btn btn-danger btn-sm" href="<?=base_url()?>/admin/actions/testimonial-update-action.php?id=<?=$this->data['testimonial_details']['id']?>&action=rejected">Reject</a>   

            </div> 


        </div>
      </div>
    </div>
   