<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">User Testimonials</h2>
         
        <div class="col-md-12  widget-shadow">
          <div class="panel-default">
            <div class="panel-heading">
              Inbox 
            </div>
            <div class="inbox-page"> 


          <?php if(empty($this->data['testimonials'])) { ?> <p> No Testimonials! </p> <?php } ?>

          <?php foreach ($this->data['testimonials'] as $testimonial ) {

            $testimonial_date=date_create($testimonial['created_at']);  ?>  

          <div class="inbox-row widget-shadow" id="accordion<?=$testimonial['id']?>" role="tablist" aria-multiselectable="true"> 
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?=$testimonial['id']?>" aria-expanded="true" aria-controls="collapse<?=$testimonial['id']?>">
              <div class="mail"><p><?=$testimonial['user_type']?> (<?=$testimonial['status']?>) </p></div>
            </a>
            <div class="mail-right dots_drop">
              <div class="dropdown">
                <a href="#"  data-toggle="dropdown" aria-expanded="false">
                  <p><i class="fa fa-ellipsis-v mail-icon"></i></p>
                </a>
                <ul class="dropdown-menu float-right">  
                  <li>
                    <a href="#" class="font-red" title="">
                      <i class="fa fa-file-o mail-icon"></i>
                      Approve
                    </a>
                  </li>
                  <li>
                    <a href="#" class="font-red" title="">
                      <i class="fa fa-trash-o mail-icon"></i>
                      Reject
                    </a>
                  </li>
                </ul>
              </div> 
            </div>
            <div class="mail-right"><p><?=date_format($testimonial_date,"M/d");?></p></div>
            <div class="clearfix"> </div> 
            <div id="collapse<?=$testimonial['id']?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<?=$testimonial['id']?>">
              <div class="mail-body">
                <p><?=$testimonial['description']?></p> 
              </div>
            </div>
          </div>

          <?php } ?>

          </div>
        </div>  
        </div>
        <div class="clearfix"> </div> 
      </div>
        
      </div>
    </div>