 
    
    <div class="hero-wrap js-fullheight" style="background-image: url('<?=$this->data['assets']?>/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">About</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-about d-md-flex">
    	<div class="one-half img" style="background-image: url(<?=$this->data['assets']?>/images/about.jpg);"></div>
    	<div class="one-half ftco-animate">
        <div class="heading-section ftco-animate ">
          <h2 class="mb-4"><span>We Are The Job Portal Agency</span></h2>
        </div>
        <div>
  				<p>We are the job portal agencies we are offering best job for your future.create an account in TalenTick and get notifications of the eligible jobs.After creating an account update your profile according to the profile we sent you the jobs.We are offering jobs from the low level company to the very reputed companies you can login this with 100 safety.....
          You get deserve jobs 
          Happy moments <a href="#">Click here </a></p>
  			</div>
    	</div>
    </section> 