
    <div class="hero-wrap js-fullheight" style="background-image: url('<?=$this->data['assets']?>/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.php">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Login</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Login</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
			<form action="<?=base_url()?>/actions/authenticate.php" name="loginform"method="post" class="p-5 bg-white">

       

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="email">Username</label>
                  <input type="email" id="email"  name="email" class="form-control" placeholder="Your Registerd Email Id" onchange="return ValidateEmail()" required="required">
                     <label class="errormail" style="display:none; color:red" id="email"></label>
                      <div id="email_error" style="color:red;">  </div>
                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="password">Password</label>
                  <input type="password" id="password" name="password" class="form-control" required="required">
                  

                </div>
              </div>

               <?php if($this->data['login_error']) {?>
                      <div class="row">
                         <div class="col-md-12 mb-3 mb-md-0"> 
                          <label style="color: red;" class="font-weight-bold" for="password">Error: <?=$this->data['login_error']?></label> </div>
                      </div>
                <?php } ?>    

              <div class="row form-group"> 
                <div class="col-md-8 mb-3 mb-md-0">
                    <button class="btn btn-success" type="submit"  > Login  </button>
                </div> 
                <div class="col-md-4 mb-3 mb-md-0">

                  <a href="<?=base_url()?>/forgot-password.php">Forgot Passowrd?</a> 
                  
                </div>

              </div> 
  
            </form>
          </div>
 
        </div>
      </div>
    </div>

		
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
              <h2>Subcribe to our Newsletter</h2>
              <p>Subscribe today to receive latest job updates and notifications</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <script type="text/javascript">
var  reg_form = document.login_form;

function ValidateEmail(){
  document.getElementById('email_error').innerHTML = "" ;
 var email = document.getElementById('email');
   var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
   if (!filter.test(email.value)) 
{
    email.value="";
    document.getElementById('email').focus();
    document.getElementById('email_error').innerHTML ="Error: Please enter email!" ; 
    
    return false;
    }
return true;
}


</script>