
 

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
      <form action="<?=base_url()?>/actions/student-registration.php" method="post" name="registration_form"class="p-5 bg-white">
              
              
              <div class="row form-group">
                <div class="col-md-10 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="firstname">Credit/Debit Card</label>
                  <input type="text" id="firstname"  name="firstname" class="form-control" placeholder="Your FirstName " onchange="return validatefirstname()" required="required">
                                    <label class="errortext" style="display:no ne; color:red" id="firstname"></label>
                                    <div id="firstname_error" style="color:red;">  </div>
                                                      
                </div>

                 <div class="col-md-2 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="firstname">CVV</label>
                  <input type="password" id="firstname"  name="firstname" class="form-control" placeholder="Your FirstName " onchange="return validatefirstname()" required="required">
                                    <label class="errortext" style="display:no ne; color:red" id="firstname"></label>
                                    <div id="firstname_error" style="color:red;">  </div>
                                                      
                </div>

              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="lastname">Name on Card</label>
                  <input type="text" id="lastname"  name="lastname" class="form-control" placeholder="Your LastName"  onchange="return validatelastname()"required="required">
                                  <label class="errortext" style="display:nne; color:red" id="lastname"></label>
                                  <div id="lastname_error" style="color:red;">  </div>


                </div>
              </div>
 
              

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="mobile_number">Mobile Number</label>
                  <input type="text" id="mobile_number"  name="mobile_number" class="form-control" placeholder="Your Phone Number" onchange="return validateMobile()"required="true">
                   <label class="errormob" style="display:none; color:red" id="mobile_number"></label><br>
                                                                 <div id="mobile_number_error" style="color:red;">  </div>

                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="password">OTP</label>
                  <input type="password" id="password" name="password" class="form-control" onchange="Validatepass()" required="required">
                          <label class="errortext" style="display:nne; color:red" id="pass"></label>
                          <div id="password_error" style="color:red;">  </div>
                                              
                </div>
              </div>


                <div class="row form-group"> 
                <div class="col-md-12 mb-3 mb-md-0">
                    <button class="btn btn-success" type="submit"  > Make Payment  </button>
                </div> 

            

              <div class="row form-group"> 
                <div class="col-md-12 mb-3 mb-md-0">
                    <button class="btn btn-success" type="submit"  > Register  </button>
                </div> 
  
            </form>
          </div>
 
        </div>
      </div>
    </div>

     

 

