
    <div class="hero-wrap js-fullheight" style="background-image: url('<?=$this->data['assets']?>/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.php">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Register</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Student Registration</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
			<form action="student-registration.php" method="post" class="p-5 bg-white">
              
              
              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="username">FirstName</label>
                  <input type="email" id="username"  name="username" class="form-control" placeholder="Your Registerd Email Id" required="required">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="username">LastName</label>
                  <input type="email" id="username"  name="username" class="form-control" placeholder="Your Registerd Email Id" required="required">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                	<label class="font-weight-bold" for="gender">Gender</label>
					<select class="form-control" name="gender" id="gender" required="required"> 
					<option value="Male">Male</option>
					<option value="Female">Female</option>
					</select>
				</div>
			   </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="email">Email ID</label>
                  <input type="email" id="email"  name="email" class="form-control" placeholder="Your Registerd Email Id" required="required">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="email">Phone Number</label>
                  <input type="email" id="text"  name="email" class="form-control" placeholder="Your Registerd Email Id" required="required">
                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="password">Password</label>
                  <input type="password" id="password" name="password" class="form-control" required="required">
                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="confirmpassword">Confirm Password</label>
                  <input type="confirmpassword" id="confirmpassword" name="confirmpassword" class="form-control" required="required">
                </div>
              </div>

              <div class="row form-group"> 
                <div class="col-md-12 mb-3 mb-md-0">
                    <button class="btn btn-success" type="submit"  > Register  </button>
                </div> 
  
            </form>
          </div>
 
        </div>
      </div>
    </div>

		
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
              <h2>Subcribe to our Newsletter</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>