
    <div class="hero-wrap js-fullheight" style="background-image: url('<?=$this->data['assets']?>/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.php">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Register</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Recruiter Registration</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
			<form action="<?=base_url()?>/actions/recruiter-registration.php" method="post" class="p-5 bg-white">


        <!--  `user_id`, `username`, `password`, `type`, `status`, `created_at`, `updated_at`
         `recruiter_id`, `user_id`, `company_name`, `email`, `website`, `phone`, `address`, `license`, `city`, `pincode` -->
              
              
              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="company_name">Company/Organization </label>
                  <input type="text" id="company_name"  name="company_name" class="form-control" placeholder="Your Company/Organization name " required="required">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="phone">Phone Number</label>
                  <input type="text" id="phone"  name="phone" class="form-control" placeholder="Your Official Phone Number" required="required">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="address">Address</label>
                  <input type="text" id="address"  name="address" class="form-control" placeholder="Your Company Address" required="required">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="city">City</label>
                  <input type="text" id="city"  name="city" class="form-control" placeholder="Your City" required="required">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="pincode">PinCode</label>
                  <input type="text" id="pincode"  name="pincode" class="form-control" placeholder="Your PinCode" required="required">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="license">Licence/Registration</label>
                  <input type="text" id="text"  name="license" class="form-control" placeholder="Your License/Registration " required="required">
                </div>
              </div>

               <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="website">Company Website</label>
                  <input type="text" id="website"  name="website" class="form-control" placeholder="Your Company Website" required="required">
                </div>
              </div> 

               <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="email">Company Email ID</label>
                  <input type="email" id="email"  name="email" class="form-control" placeholder="Your Company Email Id" required="required">
                </div>
              </div> 
 

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="username">Email ID/Username</label>
                  <input type="email" id="email"  name="username" class="form-control" placeholder="Your Email Id" required="required">
                </div>
              </div> 

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="password">Password</label>
                  <input type="password" id="password" name="password" class="form-control" required="required">
                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="confirmpassword">Confirm Password</label>
                  <input type="password" id="confirmpassword" name="confirmpassword" class="form-control" required="required">
                </div>
              </div>

              <div class="row form-group"> 
                <div class="col-md-12 mb-3 mb-md-0">
                    <button class="btn btn-success" type="submit"  > Register  </button>
                </div> 
  
            </form>
          </div>
 
        </div>
      </div>
    </div>

		
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
              <h2>Subcribe to our Newsletter</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>