
    <div class="hero-wrap js-fullheight" style="background-image: url('<?=$this->data['assets']?>/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.php">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Register</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Student Registration</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
			<form action="<?=base_url()?>/actions/student-registration.php" method="post" id="registration_form" name="registration_form"class="p-5 bg-white">
              
              
              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="firstname">FirstName</label>
                  <input type="text" id="firstname"  name="firstname" class="form-control" placeholder="Your FirstName " onchange="return validatefirstname()" required="required">
                                    <label class="errortext" style="display:no ne; color:red" id="firstname"></label>
                                    <div id="firstname_error" style="color:red;">  </div>
                                                      
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="lastname">LastName</label>
                  <input type="text" id="lastname"  name="lastname" class="form-control" placeholder="Your LastName"  onchange="return validatelastname()"required="required">
                                  <label class="errortext" style="display:nne; color:red" id="lastname"></label>
                                  <div id="lastname_error" style="color:red;">  </div>


                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                	<label class="font-weight-bold" for="gender">Gender</label>
					<select class="form-control" name="gender" id="gender" required="required"> 
					<option value="Male">Male</option>
					<option value="Female">Female</option>
					</select>
				</div>
			   </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="email">Email ID</label>
                  <input type="email" id="email"  name="email" class="form-control" placeholder="Your Email Id" onchange="return validateEmail()" required="required">
                                              <label class="errormail" style="display:none; color:red" id="email"></label>
                                              <div id="email_error" style="color:red;">  </div>
                     
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="mobile_number">Mobile Number</label>
                  <input type="text" id="mobile_number"  name="mobile_number" class="form-control" placeholder="Your Phone Number" onchange="return validateMobile()"required="true">
                   <label class="errormob" style="display:none; color:red" id="mobile_number"></label><br>
                                                                 <div id="mobile_number_error" style="color:red;">  </div>

                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="password">Password</label>
                  <input type="password" id="password" name="password" class="form-control" onchange="Validatepass()" required="required">
                  <label class="errortext" style="display:nne; color:red" id="pass"></label>
                  <div id="password_error" style="color:red;">  </div>
                </div>
             
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="confirmpassword">Confirm Password</label>
                  <input type="password" id="confirmpassword" name="confirmpassword" class="form-control" onchange="validatecpass()" required="required">
                  <label class="errortext" style="display:nne; color:red" id="cpass"></label>
                  <div id="cpassword_error" style="color:red;">  </div>
                </div>
              </div>


              <div>
                <h2>Make Payment : <?=$this->data['registration_fees']?> ₹</h2>
              </div>

                <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="card_no">Credit/Debit Card Number</label>
                  <input type="Number" id="card_no" minlength="16" name="card_no" class="form-control" placeholder="Credit/Debit Card Number" onchange="return validatecardno()" required="required">
                                    <label class="errortext" style="display:no ne; color:red" id="card_no"></label>
                                    <div id="card_no_error" style="color:red;">  </div>
                                                      
                </div>

                 <div class="col-md-2 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="cvv">CVV</label>
                  <input type="password" id="cvv"  name="cvv" class="form-control" placeholder="CVV" minlength="3" maxlength="3" onchange="return validatecvv()" required="required">
                                    <label class="errortext" style="display:no ne; color:red" id="cvv"></label>
                                    <div id="cvv_error" style="color:red;">  </div>
                                                      
                </div>

              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="card_name">Name on Card</label>
                  <input type="text" id="card_name"  name="card_name" class="form-control" placeholder="Name on Card"   onchange="return validatecardname()"required="required">
                                  <label class="errortext" style="display:nne; color:red" id="card_name"></label>
                                  <div id="card_name_error" style="color:red;">  </div>


                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-4 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="month_expiry">Month of Expiry</label>
                  <select name="month_expiry" id="month_expiry" class="form-control1" onchange="updateDistricts()" >
                      <option >--Select Month--</option>  
                      <?php foreach ($this->data['months'] as $month_data ) { ?>
                       <option value="<?=$month_data['month'] ?>" ><?=$month_data['month_display'] ?></option> 
                       <?php }?>
                    </select>
                    <label class="errortext" style="display:no ne; color:red" id="firstname"></label>
                    <div id="firstname_error" style="color:red;">  </div>
                                                      
                </div>

                 <div class="col-md-4 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="year_expiry">Year of Expiry</label>
                  <select name="year_expiry" id="year_expiry" class="form-control1" onchange="updateDistricts()" >
                      <option >--Select Year--</option>  
                      <?php foreach ($this->data['years'] as $year_data ) { ?>
                       <option value="<?=$year_data['year'] ?>" ><?=$year_data['year'] ?></option> 
                       <?php }?>
                    </select>
                    <label class="errortext" style="display:no ne; color:red" id="firstname"></label>
                    <div id="firstname_error" style="color:red;">  </div>
                                                      
                </div>

              </div> 

               <div class="row form-group"> 
                <div class="col-md-12 mb-3 mb-md-0">
                    <button class="btn btn-success" type="button"  data-toggle="modal" data-target="#otpModal"  > Register </button>
                </div> 
              </div> 
  
            </form>
          </div>
 
        </div>
      </div>
    </div>


<!-- Modal -->
<div id="otpModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Verify OTP</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form id="otp_form" class="form-horizontal">
          <p>Please check your registerd phone for the payment OTP </p>

          <div class="form-group">
            <label for="otp" class="col-sm-2 control-label">OTP</label>
            <div class="col-md-2">
            <input type="password" name="otp" id="otp"  class="form-control1" minlength="6" maxlength="6" >
            </div>
            <div class="col-md-2">
            <a href="#">Resend</a>
            </div>
          </div>

          <div class="form-group">
          <div class="col-sm-8"> </div>
          <div class="col-sm-2">
          <button type="button"   onclick="verifyOTP()" class="btn btn-info">  VERIFY </button>
          </div>
          </div>
        </form>
      </div> 
    </div>

  </div>
</div>

		
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
              <h2>Subcribe to our Newsletter</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
 



    <script type="text/javascript"> 

        function verifyOTP() {   

        var otp = document.getElementById('otp').value; 

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {

            //console.log(this.responseText) ;

            if(this.responseText != "") {

              var response = JSON.parse(this.responseText);  
              console.log(response) ;

              var validateionStatus = response.status;

              if(validateionStatus == "success"){

                $('#otpModal').modal('hide');

                 document.getElementById("registration_form").submit(); 

              }else{
                alert("Payment Failed! Invalid OTP") ;
              }

              
            }
          }
        };
        xmlhttp.open("GET", "<?=base_url()?>/actions/verity-otp.php?otp="+otp, true);
        xmlhttp.send();  

    } 



var  reg_form = document.registration_form;

function validatefirstname(){

  document.getElementById('firstname_error').innerHTML = "" ; 
  var firstname =reg_form.firstname.value;
  
  if(firstname==""){ 
    document.getElementById('firstname').focus();
    document.getElementById('firstname_error').innerHTML = "Error! Firstname is empty " ; 
    return false;
  }

  if ((firstname.length < 3) || (firstname.length > 30))
  {
  document.getElementById('firstname_error').innerHTML = "Error! characters between 3 and 30" ; 
  document.getElementById('firstname').focus();
  return false;
  }
  var pattern1 = new RegExp("^[a-zA-Z ]*$");
  if(!pattern1.test(document.registration_form.firstname.value))
  {
  document.getElementById('firstname_error').innerHTML ="Error: Please enter first name!" ; 
  document.registration_form.name.focus();
  return false;
  }
  return true;
}




function validatelastname()
{
  document.getElementById('lastname_error').innerHTML = "" ;
var lastname=reg_form.lastname.value;
if(lastname=="")
{

document.getElementById('lastname').focus();
document.getElementById('lastname_error').innerHTML = "Error! lastname is empty " ; 
return false;
}

if ((lastname.length < 1) || (lastname.length > 30))
{
document.getElementById('lasttname_error').innerHTML = "Error! characters between 3 and 30" ; 
document.getElementById('lastname').focus();
return false;
}
var pattern1 = new RegExp("^[a-zA-Z ]*$");
if(!pattern1.test(document.registration_form.lastname.value))
{
 document.getElementById('lastname_error').innerHTML ="Error: Please enter last name!" ; 
registration_form.name.focus();
return false;
}
return true;
}



function validateEmail()
{
  document.getElementById('email_error').innerHTML = "" ;
 var email = document.getElementById('email');
   var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
   if (!filter.test(email.value)) 
{
    email.value="";
    document.getElementById('email').focus();
    document.getElementById('email_error').innerHTML ="Error: Please enter email!" ; 
    
    return false;
    }
return true;
}



function validateMobile()
{
 document.getElementById('mobile_number_error').innerHTML = "" ;
if(document.registration_form.mobile_number.value == "" ||
isNaN(document.registration_form.mobile_number.value) ||
document.registration_form.mobile_number.value.length != 10 )
{
 document.getElementById('mobile_number_error').innerHTML = "Please provide a Mobile No upto 10 digit" ;     

  
document.getElementById('mobile_number').focus();
return false;
}
var pattern = new RegExp("^([6-9]{1})([0-9]{9})$");
if(!pattern.test(document.registration_form.mobile_number.value))
{
 document.getElementById('mobile_number_error').innerHTML = "Phone Number is invalid!" ; 
registration_form.mobile_number.focus();
return false;
}
return true;
}



function validatepass()
{
document.getElementById('password_error').innerHTML = "" ;
var o=document.forms["registration_form"]["password"].value;
if(o=="")
{
document.getElementById('password_error').innerHTML = "Please Fill password Field" ;
document.getElementById('password').focus();
return false;
}
if(o.length<8){  
document.getElementById('password_error').innerHTML = "Password must be at least 8 characters long." ;
document.getElementById('password').focus();
return false;  
}
return true
}



function validatecpass()
{
document.getElementById('cpassword_error').innerHTML = "" ;
var h=document.forms["registration_form"]["confirmpassword"].value;
if(h=="")
{
document.getElementById('cpassword_error').innerHTML = "Please Fill password Field" ;
document.getElementById('confirmpassword').focus();
return false;
}
var p = document.getElementById("password").value;
var cp = document.getElementById("confirmpassword").value;
if (p != cp) {
document.getElementById('cpassword_error').innerHTML = "Passwords do not match" ;
document.getElementById('confirmpassword').focus();
return false;
}
return (true);
}
function validatecardno()
{
 document.getElementById('card_no_error').innerHTML = "" ;
if(document.registration_form.card_no.value == "" ||
isNaN(document.registration_form.card_no.value) ||
document.registration_form.card_no.value.length != 16)
{
 document.getElementById('card_no_error').innerHTML = "Please provide a Card No upto 16 digit" ;     

  
document.getElementById('card_no').focus();
return false;
}
var pattern = new RegExp("^([1-9]{1})([0-9]{15})$");
if(!pattern.test(document.registration_form.card_no.value))
{
 document.getElementById('card_no_error').innerHTML = "Card NUmber is invalid!" ; 
registration_form.card_no.focus();
return false;
}
return true;
}
function validatecvv()
{
 document.getElementById('cvv_error').innerHTML = "" ;
if(document.registration_form.cvv.value == "" ||
isNaN(document.registration_form.cvv.value) ||
document.registration_form.cvv.value.length != 3)
{
 document.getElementById('cvv_error').innerHTML = "Please provide a Cvv upto 3 digit" ;     

  
document.getElementById('cvv').focus();
return false;
}
var pattern = new RegExp("^([1-9]{1})([0-9]{2})$");
if(!pattern.test(document.registration_form.cvv.value))
{
 document.getElementById('cvv_error').innerHTML = "CVV is invalid!" ; 
registration_form.cvv.focus();
return false;
}
return true;
}
function validatecardname(){

  document.getElementById('card_name_error').innerHTML = "" ; 
  var firstname =reg_form.card_name.value;
  
  if(firstname==""){ 
    document.getElementById('card_name').focus();
    document.getElementById('card_name_error').innerHTML = "Error! Card name is empty " ; 
    return false;
  }

  if ((card_name.length < 3) || (card_name.length > 30))
  {
  document.getElementById('card_name_error').innerHTML = "Error! characters between 3 and 30" ; 
  document.getElementById('card_name').focus();
  return false;
  }
  var pattern1 = new RegExp("^[a-zA-Z ]*$");
  if(!pattern1.test(document.registration_form.card_name.value))
  {
  document.getElementById('card_name_error').innerHTML ="Error: Please enter Card Name!" ; 
  document.registration_form.cardname.focus();
  return false;
  }
  return true;
}

</script>


