 <style type="text/css">
  .razorpay-payment-button{
    border-radius: 5px !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
    color: #fff !important;
    background-color: #28a745 !important;
    border-color: #28a745 !important;
  }
</style>

    <div class="hero-wrap js-fullheight" style="background-image: url('<?=$this->data['assets']?>/images/bg_2.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.php">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Register</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Student Registration</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
			<form action="<?=base_url()?>/actions/student-registration.php" method="post" onsubmit="return validate"id="registration_form" name="registration_form"class="p-5 bg-white">
              
              
              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="firstname">FirstName</label>
                  <input type="text" id="firstname"  name="firstname" class="form-control" placeholder="Your FirstName " onchange="return validatefirstname()" required="required">
                                    <label class="errortext" style="display:no ne; color:red" id="firstname"></label>
                                    <div id="firstname_error" style="color:red;">  </div>
                                                      
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="lastname">LastName</label>
                  <input type="text" id="lastname"  name="lastname" class="form-control" placeholder="Your LastName"  onchange="return validatelastname()"required="required">
                                  <label class="errortext" style="display:nne; color:red" id="lastname"></label>
                                  <div id="lastname_error" style="color:red;">  </div>


                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                	<label class="font-weight-bold" for="gender">Gender</label>
					<select class="form-control" name="gender" id="gender" required="required"> 
					<option value="Male">Male</option>
					<option value="Female">Female</option>
					</select>
				</div>
			   </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="email">Email ID</label>
                  <input type="email" id="email"  name="email" class="form-control" placeholder="Your Email Id" onchange="return validateEmail()" required="required">
                                              <label class="errormail" style="display:none; color:red" id="email"></label>
                                              <div id="email_error" style="color:red;">  </div>
                     
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="mobile_number">Mobile Number</label>
                  <input type="text" id="mobile_number"  name="mobile_number" class="form-control" placeholder="Your Phone Number" onchange="return validateMobile()"required="true">
                   <label class="errormob" style="display:none; color:red" id="mobile_number"></label><br>
                                                                 <div id="mobile_number_error" style="color:red;">  </div>

                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="password">Password</label>
                  <input type="password" id="password" name="password" class="form-control" onchange="validatepass()" required="required">
                  <label class="errortext" style="display:nne; color:red" id="pass"></label>
                  <div id="password_error" style="color:red;">  </div>
                </div>
             
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="confirmpassword">Confirm Password</label>
                  <input type="password" id="confirmpassword" name="confirmpassword" class="form-control" onchange="validatecpass()" required="required">
                  <label class="errortext" style="display:nne; color:red" id="cpass"></label>
                  <div id="cpassword_error" style="color:red;">  </div>
                </div>
              </div> 

              <script
                    src="https://checkout.razorpay.com/v1/checkout.js"
                    data-key="<?=$this->data['payment_key']?>"  
                    data-amount="<?=$this->data['registration_fees']?>" 
                    data-currency="<?=$this->data['currency']?>"
                    data-order_id="<?=$this->data['order_id']?>" 
                    data-buttontext="REGISTER"
                    data-name="TalenTick"
                    data-description="TalenTick Student Registration Fees" 
                    data-theme.color="#F37254"
                ></script> 

              <div class="row form-group"> 
                <div class="col-md-12 mb-3 mb-md-0"> 
                <input type="hidden" custom="Hidden Element" name="hidden">   
                </div> 
                <p>*All Registrations are mandatory to pay a fees of <?=($this->data['registration_fees']/100)?> Rs.<br> Click on the 'REGISTER' button to proceed</p>
              </div>   
  
            </form>
          </div>
 
        </div>
      </div>
    </div> 
 
		
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
              <h2>Subcribe to our Newsletter</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
 



<script type="text/javascript">  


var  reg_form = document.registration_form;

function validatefirstname(){

document.getElementById('firstname_error').innerHTML = "" ; 
var firstname =reg_form.firstname.value;

if(firstname==""){ 
document.getElementById('firstname').focus();
document.getElementById('firstname_error').innerHTML = "Error! Firstname is empty " ; 
return false;
}

if ((firstname.length < 3) || (firstname.length > 30))
{
document.getElementById('firstname_error').innerHTML = "Error! characters between 3 and 30" ; 
document.getElementById('firstname').focus();
return false;
}
var pattern1 = new RegExp("^[a-zA-Z ]*$");
if(!pattern1.test(document.registration_form.firstname.value))
{
document.getElementById('firstname_error').innerHTML ="Error: Please enter first name!" ; 
document.registration_form.name.focus();
return false;
}
document.getElementById('firstname_error').innerHTML ="";
return true;
}

function validatelastname()
{
document.getElementById('lastname_error').innerHTML = "" ;
var lastname=reg_form.lastname.value;
if(lastname=="")
{

document.getElementById('lastname').focus();
document.getElementById('lastname_error').innerHTML = "Error! lastname is empty " ; 
return false;
}

if ((lastname.length < 1) || (lastname.length > 30))
{
document.getElementById('lasttname_error').innerHTML = "Error! characters between 3 and 30" ; 
document.getElementById('lastname').focus();
return false;
}
var pattern1 = new RegExp("^[a-zA-Z ]*$");
if(!pattern1.test(document.registration_form.lastname.value))
{
document.getElementById('lastname_error').innerHTML ="Error: Please enter last name!" ; 
registration_form.name.focus();
return false;
}
document.getElementById('lastname_error').innerHTML ="";
return true;
}

function validateEmail()
{
document.getElementById('email_error').innerHTML = "" ;
var email = document.getElementById('email');
var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
if (!filter.test(email.value))
{
email.value="";
document.getElementById('email').focus();
document.getElementById('email_error').innerHTML ="Error: Please enter a valid email!" ; 
return false;
}else{
var valid_ext = ".ajce.in" ;
var v_len = valid_ext.length * -1 ;
var email_ext = email.value.slice(v_len ); 

console.log(v_len ); 
console.log(email_ext ); 

if(valid_ext != email_ext ){
//email.value="";
document.getElementById('email').focus();
document.getElementById('email_error').innerHTML ="Error: Please you your email provided by the college!" ; 
return false;
}
}
document.getElementById('email_error').innerHTML ="";
return true;
}

function validateMobile()
{
document.getElementById('mobile_number_error').innerHTML = "" ;
if(document.registration_form.mobile_number.value == "" ||
isNaN(document.registration_form.mobile_number.value) ||
document.registration_form.mobile_number.value.length != 10 )
{
document.getElementById('mobile_number_error').innerHTML = "Please provide a Mobile No upto 10 digit" ;     


document.getElementById('mobile_number').focus();
return false;
}
var pattern = new RegExp("^([6-9]{1})([0-9]{9})$");
if(!pattern.test(document.registration_form.mobile_number.value))
{
document.getElementById('mobile_number_error').innerHTML = "Phone Number is invalid!" ; 
registration_form.mobile_number.focus();
return false;
}
document.getElementById('mobile_number_error').innerHTML = "";
return true;
}

function validatepass()
{
document.getElementById('password_error').innerHTML = "" ;
var o=document.forms["registration_form"]["password"].value;
//console.log(o) ;
if(o=="")
{
document.getElementById('password_error').innerHTML = "Please Fill password Field" ;
document.getElementById('password').focus();
return false;
}
if(o.length<8){  
document.getElementById('password_error').innerHTML = "Password must be at least 8 characters long." ;
document.getElementById('password').focus();
return false;  
}
var strongRegex = new RegExp("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})");
var mediumRegex = new RegExp("^(((?=.*[a-z])(?=.*[A-Z]))|((?=.*[a-z])(?=.*[0-9]))|((?=.*[A-Z])(?=.*[0-9])))(?=.{6,})");


if( mediumRegex.test(o))
{

//console.log("strong pass") ;
document.getElementById('password_error').innerHTML = "" ;

} 
else
{ 
document.getElementById('password_error').innerHTML="Week Password! Password must contain alpabets, numbers & special characters";
document.getElementById("password").focus();
return false;
}
document.getElementById('password_error').innerHTML="";
return true;
}

function validatecpass()
{
document.getElementById('cpassword_error').innerHTML = "" ;
var h=document.forms["registration_form"]["confirmpassword"].value;
if(h=="")
{
document.getElementById('cpassword_error').innerHTML = "Please Fill password Field" ;
document.getElementById('confirmpassword').focus();
return false;
}
var p = document.getElementById("password").value;
var cp = document.getElementById("confirmpassword").value;
if (p != cp) {
document.getElementById('cpassword_error').innerHTML = "Passwords do not match" ;
document.getElementById('confirmpassword').focus();
return false;
}
document.getElementById('cpassword_error').innerHTML = "";
return (true);
}
 
</script>


