    <!--footer-->
    <div class="footer">
       <p>&copy; 2018 Glance Design Dashboard. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">w3layouts</a></p>
     </div>
        <!--//footer-->
  </div>
  
  <!-- side nav js -->
  <script src='<?=$this->data['assets']?>/js/SidebarNav.min.js' type='text/javascript'></script>
  <script>
      $('.sidebar-menu').SidebarNav()
    </script>
  <!-- //side nav js -->
   
  
  <!--scrolling js-->
  <script src="<?=$this->data['assets']?>/js/jquery.nicescroll.js"></script>
  <script src="<?=$this->data['assets']?>/js/scripts.js"></script>
  <!--//scrolling js-->
 
<?php switch ($this->data['page']) {
  case 'dashboard':  ?> 

  <?php break; }?>

  
  <!-- Bootstrap Core JavaScript -->
  <script src="<?=$this->data['assets']?>/js/bootstrap.js"> </script>  
  <script src="<?=$this->data['assets']?>/js/jquery.dataTables.min.js"> </script>
  <script src="<?=$this->data['assets']?>/js/dataTables.bootstrap.min.js "> </script>

  <script type="text/javascript">
    $(document).ready(function() {
      $('#datatable').DataTable(); 
    } );
  </script> 

   
</body>
</html>