<!-- main content start-->

<!-- `jobs` WHERE 1 `id`, `recruiter`, `job_title`, `job_description`, `job_type`, `state_id`, `district_id`, `last_date_to_apply`, `backlog_count`, `CGPA_min`, `CGPA_max`, `salary_min`, `salary_max`, `vacancies`, `status`, `created_at`, `updated_at`
 -->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="forms">
          <h2 class="title1">Post Jobs</h2> 

          <div class="row"> 
            <div class="form-three widget-shadow">
              <form action="<?=base_url()?>/recruiter/actions/job-post-action.php" method="post" class="form-horizontal">

                <div class="form-group">
                  <label for="job_title" class="col-sm-2 control-label">Job Title</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" name="job_title" id="job_title" placeholder="Job Title" required="required">
                  </div>
                </div>
                
                <div class="form-group">
                  <label for="job_description" class="col-sm-2 control-label">job_description</label>
                  <div class="col-sm-8"><textarea name="job_description" id="job_description" cols="50" rows="4" class="form-control1"></textarea></div>
                </div> 

                <div class="form-group">
                  <label for="job_type" class="col-sm-2 control-label"> Select Job Type</label>
                  <div class="col-sm-8"><select name="job_type" id="job_type" class="form-control1">
                    <option>Lorem ipsum dolor sit amet.</option>
                    <option>Dolore, ab unde modi est!</option>
                    <option>Illum, fuga minus sit eaque.</option>
                    <option>Consequatur ducimus maiores voluptatum minima.</option>
                  </select></div>
                </div>

                <div class="form-group">
                  <label for="state_id" class="col-sm-2 control-label">  Select State </label>
                  <div class="col-sm-8"><select name="state_id" id="state_id" class="form-control1">
                    <option>Lorem ipsum dolor sit amet.</option>
                    <option>Dolore, ab unde modi est!</option>
                    <option>Illum, fuga minus sit eaque.</option>
                    <option>Consequatur ducimus maiores voluptatum minima.</option>
                  </select></div>
                </div>

                <div class="form-group">
                  <label for="district_id" class="col-sm-2 control-label">  Select District </label>
                  <div class="col-sm-8"><select name="selector1" id="selector1" class="form-control1">
                    <option>Lorem ipsum dolor sit amet.</option>
                    <option>Dolore, ab unde modi est!</option>
                    <option>Illum, fuga minus sit eaque.</option>
                    <option>Consequatur ducimus maiores voluptatum minima.</option>
                  </select></div>
                </div> 


                <div class="form-group">
                  <label for="backlog_count" class="col-sm-2 control-label">backlog_count</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" name="backlog_count" id="backlog_count" placeholder="Job Title" required="required">
                  </div>
                </div>


                <div class="form-group">
                  <label for="CGPA_min" class="col-sm-2 control-label">CGPA_min</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" name="CGPA_min" id="CGPA_min" placeholder="CGPA_min" required="required">
                  </div>
                </div>


                <div class="form-group">
                  <label for="CGPA_max" class="col-sm-2 control-label">CGPA_max</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" name="CGPA_max" id="CGPA_max" placeholder="CGPA_max" required="required">
                  </div>
                </div>


                <div class="form-group">
                  <label for="salary_min" class="col-sm-2 control-label">salary_min</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" name="salary_min" id="salary_min" placeholder="salary_min" required="required">
                  </div>
                </div>


                <div class="form-group">
                  <label for="salary_max" class="col-sm-2 control-label">salary_max</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" name="salary_max" id="salary_max" placeholder="salary_max" required="required">
                  </div>
                </div>  


                <div class="form-group">
                  <label for="last_date_to_apply" class="col-sm-2 control-label">last_date_to_apply</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" name="last_date_to_apply" id="last_date_to_apply" placeholder="last_date_to_apply" required="required">
                  </div>
                </div>


                <div class="form-group">
                  <label for="vacancies" class="col-sm-2 control-label">vacancies</label>
                  <div class="col-sm-8">
                    <input type="number" class="form-control1" name="vacancies" id="vacancies" placeholder="Job Title" value="1" required="required">
                  </div>
                </div>

                 <?php if( isset($this->data['job']) && !empty ($this->data['job']) ) { ?>

                <div class="form-group">
                  <label for="description" class="col-sm-2 control-label">Status</label>
                  <div class="col-sm-8"> <?=$this->data['job']['status']?> </div>
                </div>

                <input type="hidden"  name="action" value="update">
                <input type="hidden"  name="id" value="<?=$this->data['job']['id']?>">

                <?php } ?>


                <div class="form-group"> 
                  <div class="col-sm-8"> </div>
                  <div class="col-sm-2">
                    <input type="submit" class="btn btn-info" name="submit" value="Post Job">
                  </div>
                </div> 


              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>