<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="forms">
          <h2 class="title1">Update Profile</h2> 

          <div class="row"> 
            <div class="form-three widget-shadow">

              <form action="<?=base_url()?>/recruiter/actions/profile-update-action.php" method="post" class="form-horizontal">

                <div class="form-group">
                  <label for="company_name" class="col-sm-2 control-label">Company Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="company_name" name="company_name"  value="<?=$this->data['profile_details']['company_name']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="email" name="email"  value="<?=$this->data['profile_details']['email']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="website" class="col-sm-2 control-label">Website  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="website" name="website"  value="<?=$this->data['profile_details']['website']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="phone" class="col-sm-2 control-label">Phone  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="phone" name="phone"  value="<?=$this->data['profile_details']['phone']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="address" class="col-sm-2 control-label">Address  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="address" name="address"  value="<?=$this->data['profile_details']['address']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="license" class="col-sm-2 control-label">License  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="license" name="license"  value="<?=$this->data['profile_details']['license']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="city" class="col-sm-2 control-label">City  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="city" name="city"  value="<?=$this->data['profile_details']['city']?> " >
                  </div>
                </div>

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Pincode  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="pincode" name="pincode"  value="<?=$this->data['profile_details']['pincode']?> " >
                  </div>
                </div> 


                <div class="form-group"> 
                  <label for="pincode" class="col-sm-2 control-label">   </label>
                  <div class="col-sm-8">
                    <input type="hidden" name="user_id" value="<?=$this->data['profile_details']['user_id']?> " >
                    <input type="hidden" name="status" value="<?=$this->data['profile_details']['status']?> " >
                    <input type="submit" class="btn btn-info"  value="Update Profile" >
                  </div>
                </div> 

 
  
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>