<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="forms">
          <h2 class="title1">Update Profile</h2> 

          <div class="row"> 
            <div class="form-three widget-shadow">

              <form enctype='multipart/form-data' action="<?=base_url()?>/recruiter/actions/profile-update-action.php" method="post" name="update_form" class="form-horizontal"   >

                <div class="form-group">
                  <label for="company_name" class="col-sm-2 control-label">Company Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control1" id="company_name" onchange= "return ValidateCompanyName()"name="company_name"  value="<?=$this->data['profile_details']['company_name']?> "  />
                                                        <label class="errortext" style="display:no ne; color:red" id="company_name"></label>
                                    <div id="company_error" style="color:red;">  </div>

                  </div>
                </div> 

                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="email" onchange="Validate_email()" name="email"  value="<?=$this->data['profile_details']['email']?> "  />
                                        <label class="errortext" style="display:no ne; color:red" id="email"></label>
                                    <div id="email_error" style="color:red;">  </div>
                  </div>
                </div> 

                <div class="form-group">
                  <label for="website" class="col-sm-2 control-label">Website  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="website" name="website"  value="<?=$this->data['profile_details']['website']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="phone" class="col-sm-2 control-label">Phone  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="phone" onchange="Validate_mobile()" name="phone"  value="<?=$this->data['profile_details']['phone']?> " >
                    <label class="errortext" style="display:no ne; color:red" id="phone"></label>
                                    <div id="phone_error" style="color:red;">  </div>
                  </div>
                </div> 

                <div class="form-group">
                  <label for="address" class="col-sm-2 control-label">Address  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="address" name="address"  value="<?=$this->data['profile_details']['address']?> " >
                  </div>
                </div> 

                <div class="form-group">
                  <label for="license" class="col-sm-2 control-label">License  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" id="license" name="license"  value="<?=$this->data['profile_details']['license']?> "  />
                  </div>
                </div> 

                <div class="form-group">
                  <label for="city" class="col-sm-2 control-label">City  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" onchange="return ValidateCity()" id="city" name="city"  value="<?=$this->data['profile_details']['city']?> " />
                    <label class="errortext" style="display:no ne; color:red" id="city"></label>
                  <div id="city_error" style="color:red;">  </div>
                  </div>
                </div>

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Pincode  </label>
                  <div class="col-sm-8">
                    <input type="text" required="required" class="form-control1" onchange="return ValidatePincode()" id="pincode" name="pincode"  value="<?=$this->data['profile_details']['pincode']?> "  />
                     <label class="errortext" style="display:no ne; color:red" id="pincode"></label>
                  <div id="pincode_error" style="color:red;">  </div>
                  </div>
                </div> 

                
                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Licence File  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" id="license_file" name="license_file" 
                    <?=(!empty($this->data['profile_details']['license_file']))? "" : ' required="required"'?>  accept="pdf"  >
                  </div>
                  <div class="col-sm-4"> 
                    <?php if (isset($this->data['profile_details']['license_file'])) { ?> 
                   
                    <a href="<?=base_url()?>/uploads/licenses/<?=$this->data['profile_details']['license_file']?>"> <i class="fa fa-file"></i> View Licence </a>
                  <?php } ?>

                  </div> 
                </div>  

                <div class="form-group">
                  <label for="pincode" class="col-sm-2 control-label">Image  </label>
                  <div class="col-sm-4">
                    <input type="file" class="" type="file" accept="png" id="image" name="image" >
                  </div>
                  <div class="col-sm-4"> 
                    <img src="<?=base_url()?>/uploads/images/<?=$this->data['profile_details']['image']?>">
                  </div> 
                </div>  



                <div class="form-group"> 
                  <label for="pincode" class="col-sm-2 control-label">   </label>
                  <div class="col-md-8"></div>
                   <div class="col-md-4">
                    <input type="hidden" name="user_id" value="<?=$this->data['profile_details']['user_id']?> " >
                    <input type="hidden" name="status" value="<?=$this->data['profile_details']['status']?> " >
                    <input type="submit" class="btn btn-info"  value="Update Profile" >
                  </div>
                </div> 

 
  
              </form>
            </div>
          </div>
          
        </div>
      </div>
    </div>
    <script type="text/javascript">
var  up_form = document.update_form;

function ValidateCompanyName(){

  document.getElementById('company_error').innerHTML = "" ; 
  var company_name =up_form.company_name.value;
  
  if(company_name==""){ 
    document.getElementById('company_name').focus();
    document.getElementById('company_error').innerHTML = "Error! company Name is empty " ; 
    return false;
  }

  if ((company_name.length < 3) || (company_name.length > 30))
  {
  document.getElementById('company_error').innerHTML = "Error! characters between 3 and 30" ; 
  document.getElementById('company_name').focus();
  return false;
  }
  var pattern1 = new RegExp("^[a-zA-Z ]*$");
  if(!pattern1.test(document.update_form.company_name.value))
  {
  document.getElementById('company_error').innerHTML ="Error: Please enter Company Name!" ; 
  document.update_form.name.focus();
  return false;
  } 
  return true;
}
function Validate_email()
{
  document.getElementById('email_error').innerHTML = "" ;
 var email = document.getElementById('email');
   var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
   if (!filter.test(email.value)) 
{
    email.value="";
    document.getElementById('email').focus();
    document.getElementById('email_error').innerHTML ="Error: Please enter email!" ; 
    
    return false;
    }
return true;
}
function Validate_mobile()
{
 document.getElementById('phone_error').innerHTML = "" ;
if(document.update_form.phone.value == "" ||
isNaN(document.update_form.phone.value) ||
document.update_form.phone.value.length != 10 )
{
 document.getElementById('phone_error').innerHTML = "Please provide a Mobile No upto 10 digit" ;     

  
document.getElementById('phone').focus();
return false;
}
var pattern = new RegExp("^([6-9]{1})([0-9]{9})$");
if(!pattern.test(document.update_form.phone.value))
{
 document.getElementById('phone_error').innerHTML = "Phone Number is invalid!" ; 
update_form.phone.focus();
return false;
}
return true;
}
function ValidateCity(){

  document.getElementById('city_error').innerHTML = "" ; 
  var city_error =reg_form.city.value;
  
  if(city==""){ 
    document.getElementById('city').focus();
    document.getElementById('city_error').innerHTML = "Error! City  is empty " ; 
    return false;
  }

  
  var pattern1 = new RegExp("^[a-zA-Z ]*$");
  if(!pattern1.test(document.registration_form.city.value))
  {
  document.getElementById('city_error').innerHTML ="Error: Please enter City!" ; 
  document.registration_form.name.focus();
  return false;
  }
  return true;
}
function ValidatePincode()
{
 document.getElementById('pincode_error').innerHTML = "" ;
if(document.registration_form.pincode.value == "" ||
isNaN(document.registration_form.pincode.value) ||
document.registration_form.pincode.value.length != 6 )
{
 document.getElementById('pincode_error').innerHTML = "Please provide a valid pincode with 6 digits" ;     

  
document.getElementById('pincode').focus();
return false;
}
var pattern = new RegExp("^([1-9]{1})([0-9]{5})$");
if(!pattern.test(document.registration_form.pincode.value))
{
 document.getElementById('pincode_error').innerHTML = "Pincode is invalid!" ; 
registration_form.pincode.focus();
return false;
}
return true;
}
</script>