<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">Profile Details</h2>
        <div class="blank-page widget-shadow scroll" id="style-2 div1">

          <?php if( isset( $this->data['profile_update_error']) ) {?>
                      <div class="row">
                         <div class="col-md-12 mb-3 mb-md-0"> 
                          <label style="color: red;" class="font-weight-bold" >Error: <?=$this->data['profile_update_error']?></label> </div>
                      </div>
                <?php } ?>    

          <p> <img src="<?=base_url()?>/uploads/images/<?=$this->data['profile_details']['image']?>">  </p> 
          <p> Company Name : <?=$this->data['profile_details']['company_name']?> </p> 
          <p> Email : <?=$this->data['profile_details']['email']?> </p> 
          <p> Website : <?=$this->data['profile_details']['website']?> </p> 
          <p> Phone : <?=$this->data['profile_details']['phone']?> </p> 
          <p> Address : <?=$this->data['profile_details']['address']?> </p> 
          <p> License : <?=$this->data['profile_details']['license']?> </p> 
          <p> City : <?=$this->data['profile_details']['city']?> </p> 
          <p> Pincode : <?=$this->data['profile_details']['pincode']?> </p> 
          <p> Status : <?=$this->data['profile_details']['status']?> </p> 
          <p> Created : <?=$this->data['profile_details']['created_at']?> </p> 

          <p> Licence File: 
              <?php if (isset($this->data['profile_details']['license_file'])) { ?> 
             
              <a href="<?=base_url()?>/uploads/licenses/<?=$this->data['profile_details']['license_file']?>"> <i class="fa fa-file"></i> View Licence </a> <?php } else{ echo "N/A"; } ?>

          </p> 

          <div>
             <a class="btn btn-info btn-sm" href="<?=base_url()?>/recruiter/profile-update.php">Update</a>  
           </div>
        </div>
      </div>
    </div>
    