<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">Job Application Details</h2>
        <div class="blank-page widget-shadow scroll" id="style-2 div1">
          <p> Job Title: <?=$this->data['application_details']['job_title']?> </p>
          <p> Job Description: <?=$this->data['application_details']['created_at']?> </p> 
          <p> JobType: <?=$this->data['application_details']['job_type']?> </p>
          <p> firstname: <?=$this->data['application_details']['firstname']?> </p>
          <p> lastname: <?=$this->data['application_details']['lastname']?> </p>
          <p> status: <?=$this->data['application_details']['status']?> </p>

          <?php if($this->data['user_data']['type'] == 'recruiter' && $this->data['application_details']['status'] == 'pending'){ ?>
            <div> <br>
              <a class="btn btn-success btn-sm" href="<?=base_url()?>/recruiter/actions/job-application-process.php?id=<?=$this->data['application_details']['id']?>&action=accepted">Accept</a>  
              
              <a class="btn btn-danger btn-sm" href="<?=base_url()?>/recruiter/actions/job-application-process.php?id=<?=$this->data['application_details']['id']?>&action=rejected">Reject</a>  
            </div>
          <?php } ?>

        </div>
       
      </div>
    </div>
   