<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <div class="tables">
          <h2 class="title1">Job List</h2>
           
          
          <div class="bs-example widget-shadow" data-example-id="hoverable-table"> 
            <h4>Hover Rows Table:</h4>
            <table id="datatable"  class="table table-hover"> 

             <!--  `id`, `recruiter`, `job_title`, -->

              <thead> <tr> 
                <th>#</th> <th>Job Title</th> <th>Job Type</th>   <th>Location</th>  <th>Posted On</th> <th>Last Date</th>  <th>Actions</th> </tr> 
              </thead> 
              <tbody> 
                <?php $i = 1;  foreach ($this->data['jobs']  as $job) { ?> 
                <tr> 
                  <th scope="row"><?=$i++?></th> 
                  <td><?=$job['job_title']?></td> 
                  <td><?=$job['JobType']?></td> 
                  <td><?=$job['District']?> (<?=$job['State']?>)</td> 
                  <td><?=date_format( date_create($job['created_at']) , "Y-M-d")?></td> 
                  <td><?=date_format( date_create($job['last_date_to_apply']) , "Y-M-d")?></td> 
                  <td> <a href="<?=base_url().'/'.$this->data['user_data']['login_type'].'/job-details.php?id='.$job['id']?>">View</a> </td> 
                </tr>  
                <?php } ?>
              </tbody> 
            </table>
          </div>
          
          
        </div>
      </div>
    </div>