<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">Job Details</h2> 
             <?=$this->data['op_status']??""?>  
        <div class="blank-page widget-shadow scroll" id="style-2 div1">
          <p> Job Title: <?=$this->data['job_details']['job_title']?> </p>
          <p> Job Description: <?=$this->data['job_details']['job_description']?> </p>
          <p> Job Details: <?=$this->data['job_details']['CGPA_min']?> </p>
          <p> Backlog Count: <?=$this->data['job_details']['backlog_count']?> </p>
          <p> Salary Min: <?=$this->data['job_details']['salary_min']?> </p>
          <p> Salary Max: <?=$this->data['job_details']['salary_max']?> </p>
          <p> Vacancies: <?=$this->data['job_details']['vacancies']?> </p>
           <?php if($this->data['user_data']['type'] == 'admin'  ){ ?> 
           <p> Total Applications : <?=$this->data['application_count']['count'] ?>   </p> 
          <?php }  ?>
          <p> Last Date to Apply: <?=$this->data['job_details']['last_date_to_apply']?> </p>

           <?php if($this->data['user_data']['type'] == 'student'){ ?>

          <p> Company Name:  <a target="_blank" href="<?=base_url().'/'.$this->data['login_type'].'/recruiter-details.php?id='.$this->data['job_details']['recruiter']?>"> <?=$this->data['job_details']['company_name']?> </a> </p>

           <?php }  ?>


          <p> JobType: <?=$this->data['job_details']['JobType']?> </p>
          <p> District: <?=$this->data['job_details']['District']?> </p>
          <p> State: <?=$this->data['job_details']['State']?> </p> 
 
            <?php if($this->data['user_data']['type'] == 'student' && !$this->data['job_application_details'] ){ ?>
            <div> <br>
              <a class="btn btn-success btn-sm" href="<?=base_url()?>/student/actions/job-apply-action.php?id=<?=$this->data['job_details']['id']?>">Apply</a>      
            </div>
          <?php } else if($this->data['user_data']['type'] == 'student'){ ?>

          <p> Application Status : <?=$this->data['job_application_details']['status']?> </p>

          <?php }  ?>



        </div>
      </div>
    </div>
   