<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">Notifications Page</h2>
         
        <div class="col-md-12  widget-shadow">
          <div class="panel-default">
            <div class="panel-heading">
              Inbox 
            </div>
            <div class="inbox-page"> 


          <?php if(empty($this->data['notifications'])) { ?> <p> No Notifications! </p> <?php } ?>

          <?php foreach ($this->data['notifications'] as $notification ) {

            $notification_date=date_create($notification['created_at']);  ?>  

          <div class="inbox-row widget-shadow" id="accordion<?=$notification['id']?>" role="tablist" aria-multiselectable="true"> 
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?=$notification['id']?>" aria-expanded="true" aria-controls="collapse<?=$notification['id']?>">
              <div class="mail"><p><?=$notification['title']?></p></div>
            </a>
             
            <div class="mail-right"><p><?=date_format($notification_date,"M/d");?></p></div>
            <div class="clearfix"> </div> 
            <div id="collapse<?=$notification['id']?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<?=$notification['id']?>">
              <div class="mail-body">
                <p><?=$notification['description']?></p>
                <?php if( !empty($notification['action_link']) ) {?>
                <form method="get" action="<?=base_url().'/'.$notification['action_link']?>"> 
                  <input type="submit" value="Details">
                </form>
              <?php } ?> 
                    
              </div>
            </div>
          </div>

          <?php } ?>

          </div>
        </div>  
        </div>
        <div class="clearfix"> </div> 
      </div>
        
      </div>
    </div>