<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page">
        <h2 class="title1">Student Details</h2>
        <div class="blank-page widget-shadow scroll" id="style-2 div1">
          <p> Job Title: <?=$this->data['job_details']['job_title']?> </p>
          <p> Job Description: <?=$this->data['job_details']['job_description']?> </p>
          <p> Job Details: <?=$this->data['job_details']['CGPA_min']?> </p>
          <p> Backlog Count: <?=$this->data['job_details']['backlog_count']?> </p>
          <p> Salary Min: <?=$this->data['job_details']['salary_min']?> </p>
          <p> Salary Max: <?=$this->data['job_details']['salary_max']?> </p>
          <p> Vacancies: <?=$this->data['job_details']['vacancies']?> </p>
          <p> Last Date to Apply: <?=$this->data['job_details']['last_date_to_apply']?> </p>
          <p> Company Name: <?=$this->data['job_details']['company_name']?> </p>
          <p> JobType: <?=$this->data['job_details']['JobType']?> </p>
          <p> District: <?=$this->data['job_details']['District']?> </p>
          <p> State: <?=$this->data['job_details']['State']?> </p>
        </div>
      </div>
    </div>
   