<!-- main content start-->
    <div id="page-wrapper">
      <div class="main-page login-page ">
        <div class="widget-shadow">
          <div class="login-body"> 

            <form action="<?=base_url()?>/actions/update-password-action.php" method="post" onsubmit="return checkPassword()">
              <input type="password" id="current_password" name="current_password" class="lock" placeholder="Current Password" required="">
              <input type="password" id="new_password" name="new_password" class="lock" placeholder="New Password" required="">
              <input type="password" id="confirm_password" name="confirm_password" class="lock" placeholder="Confirm Password" required="" onblur="checkPassword()" >

              <?php echo  $_SESSION['errors']['update_password'] ?? "" ; unset( $_SESSION['errors']['update_password']); ?>

              <input type="submit" name="" value="Update Password" >

            </form>
          </div>
        </div>

      </div>
    </div>

    <script type="text/javascript">
      function checkPassword(){

        var new_password = document.getElementById('new_password').value;
        var confirm_password= document.getElementById('confirm_password').value;

        if(new_password == confirm_password){

          return true ;

        }else{

          alert("Passwords Don't Match,  Please Check")

          return false;

        }

      }
    </script>