<!DOCTYPE html>
<html lang="en">
  <head>
    <title><?=$this->data['page_title']?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/animate.css">
    
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/owl.carousel.min.css">
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/magnific-popup.css">

    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/aos.css">

    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/ionicons.min.css">

    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/jquery.timepicker.css">

    
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/flaticon.css">
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/icomoon.css">
    <link rel="stylesheet" href="<?=$this->data['assets']?>/css/style.css">
  </head>
  <body>
    
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.php">TalenTick</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="<?=base_url()?>/index.php" class="nav-link">Home</a></li>
	          <li class="nav-item"><a href="<?=base_url()?>/about.php" class="nav-link">About</a></li> 
	          	<?php if($this->data['login'] && $this->data['login_type'] != null  && $this->data['login_type'] != '' ) { ?>
	          		<li class="nav-item"><a href="<?=base_url().'/'.$this->data['login_type']?>/" class="nav-link">Dashboard</a></li>
	          	<?php } else { ?>
		          <li class="nav-item"><a href="login.php" class="nav-link">Login</a></li> 
		          <li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Register
			        <span class="caret"></span></a>
			        <ul class="dropdown-menu">
			          <li class="nav-item dropdown-item"><a class="nav-link" href="<?=base_url()?>/register-student.php">Student</a></li>
			          <li class="nav-item dropdown-item"><a class="nav-link" href="<?=base_url()?>/register-recruiter.php">Recruiter</a></li> 
			        </ul>
			      </li>
		  		<?php } ?> 
	          <li class="nav-item"><a href="<?=base_url()?>/contact.php" class="nav-link">Contact</a></li> 

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->	