<body class="cbp-spmenu-push">
  <div class="main-content">
  <div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
    <!--left-fixed -navigation-->
    <aside class="sidebar-left">
      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <h1><a class="navbar-brand" href="<?=base_url()?>/index.php"><span class="fa fa-area-chart"></span> TalenTick<span class="dashboard_text">Main Website</span></a></h1>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="sidebar-menu">
              <li class="header">MAIN NAVIGATION</li>
              <li class="treeview">
                <a href="<?=base_url()?>/student/index.php">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
              </li>  
              <li>
                <a href="<?=base_url()?>/student/notifications.php">
                  <i class="fa fa-bell"></i> <span>Notifications</span> 

                </a>
              </li> 
              <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Jobs</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="<?=base_url()?>/student/jobs-search.php"><i class="fa fa-angle-right"></i> Search Jobs</a></li>
                  <li><a href="<?=base_url()?>/student/jobs-list.php"><i class="fa fa-angle-right"></i> New Jobs List</a></li>
                  <li><a href="<?=base_url()?>/student/jobs-applied.php"><i class="fa fa-angle-right"></i> Applied Jobs</a></li> 
                </ul>
              </li> 
              <li><a href="<?=base_url()?>/student/testimonial.php"><i class="fa fa-edit text-red"></i> <span>Testimonial</span></a></li>
              <li class="header">USER</li>
              <li class="treeview">
                <a href="#">
                <i class="fa fa-user"></i>
                <span>Account</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="<?=base_url()?>/student/profile-details.php"><i class="fa fa-angle-right"></i> My Profile</a></li>
                  <li> <a href="<?=base_url()?>/student/update-password.php"><i class="fa fa-angle-right"></i> Update Password</a> </li> 
                  <li><a href="<?=base_url()?>/student/profile-update.php"><i class="fa fa-angle-right"></i> Update Profile</a></li> 
                </ul>
              </li> 
              <li><a href="<?=base_url()?>/actions/logout.php"><i class="fa fa-sign-out text-yellow"></i> <span>Logout</span></a></li> 
            </ul>
          </div>
          <!-- /.navbar-collapse -->
      </nav>
    </aside>
  </div>
    <!--left-fixed -navigation-->
    
    <!-- header-starts -->
    <div class="sticky-header header-section ">
      <div class="header-left"> 
        
        <div class="clearfix"> </div>
      </div>
      <div class="header-right">
        
        
        <div class="profile_details">   
          <ul>
            <li class="dropdown profile_details_drop">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <div class="profile_img"> 
                  <span class="prfil-img"><img src="<?=$this->data['assets']?>/images/2.jpg" alt=""> </span> 
                  <div class="user-name">
                    <p>Student Name</p>
                    <span>Profile</span>
                  </div>
                  <i class="fa fa-angle-down lnr"></i>
                  <i class="fa fa-angle-up lnr"></i>
                  <div class="clearfix"></div>  
                </div>  
              </a>
              <ul class="dropdown-menu drp-mnu">
                <!-- <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>  -->
                <li> <a href="<?=base_url()?>/student/profile-details.php"><i class="fa fa-user"></i> My Profile</a> </li>
                <li> <a href="<?=base_url()?>/student/update-password.php"><i class="fa fa-lock"></i> Update Password</a> </li> 
                <li> <a href="<?=base_url()?>/student/profile-update.php"><i class="fa fa-edit"></i> Update Profile</a> </li> 
                <li> <a href="<?=base_url()?>/actions/logout.php"><i class="fa fa-sign-out"></i> Logout</a> </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="clearfix"> </div>       
      </div>
      <div class="clearfix"> </div> 
    </div>
    <!-- //header-ends -->